/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as academy from "../academy.js";
import type * as accessAllowlist from "../accessAllowlist.js";
import type * as ai from "../ai.js";
import type * as aiActions from "../aiActions.js";
import type * as aiEngine from "../aiEngine.js";
import type * as audiences from "../audiences.js";
import type * as auth from "../auth.js";
import type * as backerMilestones from "../backerMilestones.js";
import type * as blasts from "../blasts.js";
import type * as budgetDecisionEmails from "../budgetDecisionEmails.js";
import type * as budgetDetail from "../budgetDetail.js";
import type * as budgetLines from "../budgetLines.js";
import type * as campaignApprovalEmails from "../campaignApprovalEmails.js";
import type * as campaignPolls from "../campaignPolls.js";
import type * as campaignTemplates from "../campaignTemplates.js";
import type * as campaigns from "../campaigns.js";
import type * as cards from "../cards.js";
import type * as cashAppBackfill from "../cashAppBackfill.js";
import type * as checkIns from "../checkIns.js";
import type * as columns from "../columns.js";
import type * as commsSend from "../commsSend.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboardCharts from "../dashboardCharts.js";
import type * as dashboardDrill from "../dashboardDrill.js";
import type * as dataExports from "../dataExports.js";
import type * as dataHygiene from "../dataHygiene.js";
import type * as docs from "../docs.js";
import type * as donorIdentityBackfill from "../donorIdentityBackfill.js";
import type * as doorAccess from "../doorAccess.js";
import type * as emailHtmlImport from "../emailHtmlImport.js";
import type * as emailImages from "../emailImages.js";
import type * as emailPreview from "../emailPreview.js";
import type * as emailSuppressions from "../emailSuppressions.js";
import type * as emailThemes from "../emailThemes.js";
import type * as engagements from "../engagements.js";
import type * as eventAttendanceImport from "../eventAttendanceImport.js";
import type * as eventTypes from "../eventTypes.js";
import type * as events from "../events.js";
import type * as financeGenesisBackfill from "../financeGenesisBackfill.js";
import type * as financeRoles from "../financeRoles.js";
import type * as financeSettings from "../financeSettings.js";
import type * as finances from "../finances.js";
import type * as formSubmissions from "../formSubmissions.js";
import type * as gear2024Split from "../gear2024Split.js";
import type * as genesisApproveExceptions from "../genesisApproveExceptions.js";
import type * as genesisCleanup from "../genesisCleanup.js";
import type * as genesisDedupe from "../genesisDedupe.js";
import type * as genesisGiftSync from "../genesisGiftSync.js";
import type * as genesisRevenueSync from "../genesisRevenueSync.js";
import type * as givebutterRepair from "../givebutterRepair.js";
import type * as givebutterSync from "../givebutterSync.js";
import type * as giving from "../giving.js";
import type * as givingActivity from "../givingActivity.js";
import type * as givingCandidates from "../givingCandidates.js";
import type * as givingDonations from "../givingDonations.js";
import type * as givingImport from "../givingImport.js";
import type * as givingInterest from "../givingInterest.js";
import type * as givingPlatform from "../givingPlatform.js";
import type * as givingPledges from "../givingPledges.js";
import type * as googleChatChannels from "../googleChatChannels.js";
import type * as guestTeams from "../guestTeams.js";
import type * as guests from "../guests.js";
import type * as historicalBackfill from "../historicalBackfill.js";
import type * as http from "../http.js";
import type * as identity from "../identity.js";
import type * as increase from "../increase.js";
import type * as increaseAccounts from "../increaseAccounts.js";
import type * as increaseCardArt from "../increaseCardArt.js";
import type * as increaseExternalAccounts from "../increaseExternalAccounts.js";
import type * as increaseLedger from "../increaseLedger.js";
import type * as increasePayouts from "../increasePayouts.js";
import type * as increaseProvision from "../increaseProvision.js";
import type * as integrationSettings from "../integrationSettings.js";
import type * as inventory from "../inventory.js";
import type * as items from "../items.js";
import type * as legacyCards from "../legacyCards.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_aiEngine from "../lib/aiEngine.js";
import type * as lib_assets from "../lib/assets.js";
import type * as lib_audienceResolve from "../lib/audienceResolve.js";
import type * as lib_audienceTargeting from "../lib/audienceTargeting.js";
import type * as lib_bookBalance from "../lib/bookBalance.js";
import type * as lib_builtInTemplates from "../lib/builtInTemplates.js";
import type * as lib_campaignKind from "../lib/campaignKind.js";
import type * as lib_campaignsAccess from "../lib/campaignsAccess.js";
import type * as lib_centralReach from "../lib/centralReach.js";
import type * as lib_chapters from "../lib/chapters.js";
import type * as lib_codingReminders from "../lib/codingReminders.js";
import type * as lib_commsAccess from "../lib/commsAccess.js";
import type * as lib_context from "../lib/context.js";
import type * as lib_dataExportAccess from "../lib/dataExportAccess.js";
import type * as lib_donorIdentity from "../lib/donorIdentity.js";
import type * as lib_emailCodes from "../lib/emailCodes.js";
import type * as lib_emailHtmlSanitize from "../lib/emailHtmlSanitize.js";
import type * as lib_emailShell from "../lib/emailShell.js";
import type * as lib_emlMessage from "../lib/emlMessage.js";
import type * as lib_exportBuilders_academy from "../lib/exportBuilders/academy.js";
import type * as lib_exportBuilders_eventsAndParticipation from "../lib/exportBuilders/eventsAndParticipation.js";
import type * as lib_exportBuilders_finance from "../lib/exportBuilders/finance.js";
import type * as lib_exportBuilders_formSubmissions from "../lib/exportBuilders/formSubmissions.js";
import type * as lib_exportBuilders_giving from "../lib/exportBuilders/giving.js";
import type * as lib_exportBuilders_index from "../lib/exportBuilders/index.js";
import type * as lib_exportBuilders_people from "../lib/exportBuilders/people.js";
import type * as lib_exportBuilders_types from "../lib/exportBuilders/types.js";
import type * as lib_exportBuilders_work from "../lib/exportBuilders/work.js";
import type * as lib_exportRunner from "../lib/exportRunner.js";
import type * as lib_finance from "../lib/finance.js";
import type * as lib_financeAuditLog from "../lib/financeAuditLog.js";
import type * as lib_financeEditAccess from "../lib/financeEditAccess.js";
import type * as lib_forPickerCandidates from "../lib/forPickerCandidates.js";
import type * as lib_formCatalog from "../lib/formCatalog.js";
import type * as lib_formsAccess from "../lib/formsAccess.js";
import type * as lib_giftAudit from "../lib/giftAudit.js";
import type * as lib_giveApiRoutes from "../lib/giveApiRoutes.js";
import type * as lib_givePage from "../lib/givePage.js";
import type * as lib_givePageClient from "../lib/givePageClient.js";
import type * as lib_givePageSections from "../lib/givePageSections.js";
import type * as lib_givePageStyles from "../lib/givePageStyles.js";
import type * as lib_givingAccess from "../lib/givingAccess.js";
import type * as lib_givingAudit from "../lib/givingAudit.js";
import type * as lib_givingDonors from "../lib/givingDonors.js";
import type * as lib_googleChat from "../lib/googleChat.js";
import type * as lib_guestTeams from "../lib/guestTeams.js";
import type * as lib_guides from "../lib/guides.js";
import type * as lib_html from "../lib/html.js";
import type * as lib_identityAccess from "../lib/identityAccess.js";
import type * as lib_identityEvidence from "../lib/identityEvidence.js";
import type * as lib_imageSniff from "../lib/imageSniff.js";
import type * as lib_increaseApi from "../lib/increaseApi.js";
import type * as lib_increaseExtract from "../lib/increaseExtract.js";
import type * as lib_increaseFiles from "../lib/increaseFiles.js";
import type * as lib_increasePayoutMachine from "../lib/increasePayoutMachine.js";
import type * as lib_increaseShapes from "../lib/increaseShapes.js";
import type * as lib_landingPage from "../lib/landingPage.js";
import type * as lib_landingPageClient from "../lib/landingPageClient.js";
import type * as lib_landingPageStyles from "../lib/landingPageStyles.js";
import type * as lib_landingPageVerifyClient from "../lib/landingPageVerifyClient.js";
import type * as lib_merchantSimilarity from "../lib/merchantSimilarity.js";
import type * as lib_org from "../lib/org.js";
import type * as lib_people from "../lib/people.js";
import type * as lib_peopleAggregate from "../lib/peopleAggregate.js";
import type * as lib_personEmails from "../lib/personEmails.js";
import type * as lib_personName from "../lib/personName.js";
import type * as lib_phoneCodes from "../lib/phoneCodes.js";
import type * as lib_placements from "../lib/placements.js";
import type * as lib_platformGuides from "../lib/platformGuides.js";
import type * as lib_pollPage from "../lib/pollPage.js";
import type * as lib_projectActionPage from "../lib/projectActionPage.js";
import type * as lib_publishabilityAccess from "../lib/publishabilityAccess.js";
import type * as lib_readiness from "../lib/readiness.js";
import type * as lib_receiptExceptionAccess from "../lib/receiptExceptionAccess.js";
import type * as lib_receiptExceptions from "../lib/receiptExceptions.js";
import type * as lib_receiptLinks from "../lib/receiptLinks.js";
import type * as lib_receiptRetry from "../lib/receiptRetry.js";
import type * as lib_receiptSuggestionAccess from "../lib/receiptSuggestionAccess.js";
import type * as lib_reconciliationAccess from "../lib/reconciliationAccess.js";
import type * as lib_reconciliationGap from "../lib/reconciliationGap.js";
import type * as lib_reimburseApiRoutes from "../lib/reimburseApiRoutes.js";
import type * as lib_reimbursePage from "../lib/reimbursePage.js";
import type * as lib_reimbursementTxnFields from "../lib/reimbursementTxnFields.js";
import type * as lib_resend from "../lib/resend.js";
import type * as lib_rsvpPeople from "../lib/rsvpPeople.js";
import type * as lib_salesCatalog from "../lib/salesCatalog.js";
import type * as lib_seatStructure from "../lib/seatStructure.js";
import type * as lib_seats from "../lib/seats.js";
import type * as lib_seed_fieldDay from "../lib/seed/fieldDay.js";
import type * as lib_seed_finance from "../lib/seed/finance.js";
import type * as lib_seed_helpers from "../lib/seed/helpers.js";
import type * as lib_seed_historical_cashApp2026 from "../lib/seed/historical/cashApp2026.js";
import type * as lib_seed_historical_eden from "../lib/seed/historical/eden.js";
import type * as lib_seed_historical_fieldDayTickets from "../lib/seed/historical/fieldDayTickets.js";
import type * as lib_seed_historical_gear2024Orders from "../lib/seed/historical/gear2024Orders.js";
import type * as lib_seed_historical_genesis from "../lib/seed/historical/genesis.js";
import type * as lib_seed_historical_genesisBank from "../lib/seed/historical/genesisBank.js";
import type * as lib_seed_historical_genesisCleanup2026 from "../lib/seed/historical/genesisCleanup2026.js";
import type * as lib_seed_historical_genesisDedupe2026 from "../lib/seed/historical/genesisDedupe2026.js";
import type * as lib_seed_historical_genesisInkindExpenses from "../lib/seed/historical/genesisInkindExpenses.js";
import type * as lib_seed_historical_genesisLtn from "../lib/seed/historical/genesisLtn.js";
import type * as lib_seed_historical_givebutterRepair2026 from "../lib/seed/historical/givebutterRepair2026.js";
import type * as lib_seed_historical_giving from "../lib/seed/historical/giving.js";
import type * as lib_seed_historical_ltn from "../lib/seed/historical/ltn.js";
import type * as lib_seed_historical_mapping from "../lib/seed/historical/mapping.js";
import type * as lib_seed_historical_nye from "../lib/seed/historical/nye.js";
import type * as lib_seed_historical_ptb from "../lib/seed/historical/ptb.js";
import type * as lib_seed_historical_ptbGbTickets from "../lib/seed/historical/ptbGbTickets.js";
import type * as lib_seed_historical_ptbVenmo2026 from "../lib/seed/historical/ptbVenmo2026.js";
import type * as lib_seed_historical_types from "../lib/seed/historical/types.js";
import type * as lib_seed_loveThyNeighbor from "../lib/seed/loveThyNeighbor.js";
import type * as lib_seed_roster from "../lib/seed/roster.js";
import type * as lib_seed_templates from "../lib/seed/templates.js";
import type * as lib_serviceCatalog from "../lib/serviceCatalog.js";
import type * as lib_servicesAccess from "../lib/servicesAccess.js";
import type * as lib_sha256 from "../lib/sha256.js";
import type * as lib_siteUrl from "../lib/siteUrl.js";
import type * as lib_ssrfGuard from "../lib/ssrfGuard.js";
import type * as lib_standardWebhook from "../lib/standardWebhook.js";
import type * as lib_superuser from "../lib/superuser.js";
import type * as lib_templates from "../lib/templates.js";
import type * as lib_ticketApiRoutes from "../lib/ticketApiRoutes.js";
import type * as lib_ticketingAccess from "../lib/ticketingAccess.js";
import type * as lib_tiptapCampaignRender from "../lib/tiptapCampaignRender.js";
import type * as lib_transactionCoding from "../lib/transactionCoding.js";
import type * as lib_transactionCodingAccess from "../lib/transactionCodingAccess.js";
import type * as lib_transferPair from "../lib/transferPair.js";
import type * as lib_twilio from "../lib/twilio.js";
import type * as lib_unsubscribePage from "../lib/unsubscribePage.js";
import type * as linkTruistGifts from "../linkTruistGifts.js";
import type * as maintenance from "../maintenance.js";
import type * as markPtbPayout from "../markPtbPayout.js";
import type * as migrations from "../migrations.js";
import type * as migrations_0000_seed_ledger from "../migrations/0000_seed_ledger.js";
import type * as migrations_0007_cleanup_renamed_guide_slugs from "../migrations/0007_cleanup_renamed_guide_slugs.js";
import type * as migrations_0008_cleanup_orphaned_placements from "../migrations/0008_cleanup_orphaned_placements.js";
import type * as migrations_0009_backfill_people_services from "../migrations/0009_backfill_people_services.js";
import type * as migrations_0010_backfill_template_people_teams from "../migrations/0010_backfill_template_people_teams.js";
import type * as migrations_0011_backfill_person_status from "../migrations/0011_backfill_person_status.js";
import type * as migrations_0012_materialize_how_to_docs from "../migrations/0012_materialize_how_to_docs.js";
import type * as migrations_0013_fold_project_status_notes from "../migrations/0013_fold_project_status_notes.js";
import type * as migrations_0014_copy_guest_allowlist from "../migrations/0014_copy_guest_allowlist.js";
import type * as migrations_0015_audit_column_types from "../migrations/0015_audit_column_types.js";
import type * as migrations_0016_clear_legacy_fields from "../migrations/0016_clear_legacy_fields.js";
import type * as migrations_0017_purge_guest_allowlist from "../migrations/0017_purge_guest_allowlist.js";
import type * as migrations_0018_backfill_course_completions from "../migrations/0018_backfill_course_completions.js";
import type * as migrations_0019_backfill_run_of_show_duration from "../migrations/0019_backfill_run_of_show_duration.js";
import type * as migrations_0020_permits_states_and_fallback from "../migrations/0020_permits_states_and_fallback.js";
import type * as migrations_0021_inventory_category_to_tags from "../migrations/0021_inventory_category_to_tags.js";
import type * as migrations_0022_seed_seat_defs from "../migrations/0022_seed_seat_defs.js";
import type * as migrations_0023_seed_seat_assignments from "../migrations/0023_seed_seat_assignments.js";
import type * as migrations_0024_repoint_derived_seat_duties from "../migrations/0024_repoint_derived_seat_duties.js";
import type * as migrations_0025_add_cd_finance_viewer from "../migrations/0025_add_cd_finance_viewer.js";
import type * as migrations_0026_migrate_budget_v1_lines from "../migrations/0026_migrate_budget_v1_lines.js";
import type * as migrations_0027_sync_linked_budget_identity from "../migrations/0027_sync_linked_budget_identity.js";
import type * as migrations_0028_reaward_course_completions from "../migrations/0028_reaward_course_completions.js";
import type * as migrations_0029_territories_cutover from "../migrations/0029_territories_cutover.js";
import type * as migrations_0030_backfill_launch_fund from "../migrations/0030_backfill_launch_fund.js";
import type * as migrations_0031_gift_method_sources from "../migrations/0031_gift_method_sources.js";
import type * as migrations_0032_link_donor_people from "../migrations/0032_link_donor_people.js";
import type * as migrations_0033_add_giving_power_defaults from "../migrations/0033_add_giving_power_defaults.js";
import type * as migrations_0034_merge_duplicate_gb_guests from "../migrations/0034_merge_duplicate_gb_guests.js";
import type * as migrations_0035_backfill_receipt_documents from "../migrations/0035_backfill_receipt_documents.js";
import type * as migrations_0036_add_campaign_power_defaults from "../migrations/0036_add_campaign_power_defaults.js";
import type * as migrations_0037_link_rsvp_people from "../migrations/0037_link_rsvp_people.js";
import type * as migrations_0038_backfill_contact_only_people from "../migrations/0038_backfill_contact_only_people.js";
import type * as migrations_0039_backfill_person_emails from "../migrations/0039_backfill_person_emails.js";
import type * as migrations_0040_migrate_legacy_audiences from "../migrations/0040_migrate_legacy_audiences.js";
import type * as migrations_0041_migrate_guest_audiences from "../migrations/0041_migrate_guest_audiences.js";
import type * as migrations_0042_wrap_targeting from "../migrations/0042_wrap_targeting.js";
import type * as migrations_0043_split_person_names from "../migrations/0043_split_person_names.js";
import type * as migrations_0044_reimbursement_payouts_outflow from "../migrations/0044_reimbursement_payouts_outflow.js";
import type * as migrations_0045_backfill_personal_repayments from "../migrations/0045_backfill_personal_repayments.js";
import type * as migrations_0046_seed_service_catalog from "../migrations/0046_seed_service_catalog.js";
import type * as migrations_0047_service_conditions_to_ids from "../migrations/0047_service_conditions_to_ids.js";
import type * as migrations_0048_import_form_submissions from "../migrations/0048_import_form_submissions.js";
import type * as migrations_0049_seed_builtin_campaign_templates from "../migrations/0049_seed_builtin_campaign_templates.js";
import type * as migrations_0050_link_rsvp_identifiers from "../migrations/0050_link_rsvp_identifiers.js";
import type * as migrations_0051_backfill_people_persona from "../migrations/0051_backfill_people_persona.js";
import type * as migrations_0052_import_newsletter_images from "../migrations/0052_import_newsletter_images.js";
import type * as migrations_0053_add_campaign_design_defaults from "../migrations/0053_add_campaign_design_defaults.js";
import type * as migrations_0054_seed_org_mailing_address from "../migrations/0054_seed_org_mailing_address.js";
import type * as migrations_0055_merge_campaign_templates_into_campaigns from "../migrations/0055_merge_campaign_templates_into_campaigns.js";
import type * as migrations_0056_upgrade_builtin_newsletter_tiptap from "../migrations/0056_upgrade_builtin_newsletter_tiptap.js";
import type * as migrations_0057_backfill_increase_transactions from "../migrations/0057_backfill_increase_transactions.js";
import type * as migrations_0058_add_data_export_defaults from "../migrations/0058_add_data_export_defaults.js";
import type * as migrations_0059_split_legacy_increase_cards from "../migrations/0059_split_legacy_increase_cards.js";
import type * as migrations_0060_add_events_checkin_defaults from "../migrations/0060_add_events_checkin_defaults.js";
import type * as migrations_index from "../migrations/index.js";
import type * as modules from "../modules.js";
import type * as moneyViews from "../moneyViews.js";
import type * as netOutCashGifts from "../netOutCashGifts.js";
import type * as oneoffDedupeRelay from "../oneoffDedupeRelay.js";
import type * as org from "../org.js";
import type * as people from "../people.js";
import type * as peopleImport from "../peopleImport.js";
import type * as personEmails from "../personEmails.js";
import type * as places from "../places.js";
import type * as processorFees from "../processorFees.js";
import type * as profiles from "../profiles.js";
import type * as projectActions from "../projectActions.js";
import type * as projects from "../projects.js";
import type * as ptbVenmoBackfill from "../ptbVenmoBackfill.js";
import type * as publishability from "../publishability.js";
import type * as receiptExceptions from "../receiptExceptions.js";
import type * as receiptInbox from "../receiptInbox.js";
import type * as receiptInboxBackfill from "../receiptInboxBackfill.js";
import type * as receiptPdf from "../receiptPdf.js";
import type * as receipts from "../receipts.js";
import type * as reconcileSuggest from "../reconcileSuggest.js";
import type * as reconciliation from "../reconciliation.js";
import type * as reimbursementBackfill from "../reimbursementBackfill.js";
import type * as reimbursements from "../reimbursements.js";
import type * as reminders from "../reminders.js";
import type * as responsibilities from "../responsibilities.js";
import type * as restoreTruistDeposit from "../restoreTruistDeposit.js";
import type * as reverseBadSettlement from "../reverseBadSettlement.js";
import type * as roleAssignments from "../roleAssignments.js";
import type * as roles from "../roles.js";
import type * as sales from "../sales.js";
import type * as salesSync from "../salesSync.js";
import type * as schema_academy from "../schema/academy.js";
import type * as schema_accessAllowlist from "../schema/accessAllowlist.js";
import type * as schema_ai from "../schema/ai.js";
import type * as schema_backerMilestones from "../schema/backerMilestones.js";
import type * as schema_campaigns from "../schema/campaigns.js";
import type * as schema_chapters from "../schema/chapters.js";
import type * as schema_dataExports from "../schema/dataExports.js";
import type * as schema_docs from "../schema/docs.js";
import type * as schema_events from "../schema/events.js";
import type * as schema_finances from "../schema/finances.js";
import type * as schema_forms from "../schema/forms.js";
import type * as schema_givingActivity from "../schema/givingActivity.js";
import type * as schema_givingInterest from "../schema/givingInterest.js";
import type * as schema_givingPlatform from "../schema/givingPlatform.js";
import type * as schema_googleChatChannels from "../schema/googleChatChannels.js";
import type * as schema_identity from "../schema/identity.js";
import type * as schema_integrationSettings from "../schema/integrationSettings.js";
import type * as schema_inventory from "../schema/inventory.js";
import type * as schema_migrations from "../schema/migrations.js";
import type * as schema_modules from "../schema/modules.js";
import type * as schema_people from "../schema/people.js";
import type * as schema_projects from "../schema/projects.js";
import type * as schema_responsibilities from "../schema/responsibilities.js";
import type * as schema_roles from "../schema/roles.js";
import type * as schema_seatProposals from "../schema/seatProposals.js";
import type * as schema_seatStructureLog from "../schema/seatStructureLog.js";
import type * as schema_seats from "../schema/seats.js";
import type * as schema_services from "../schema/services.js";
import type * as schema_shared from "../schema/shared.js";
import type * as schema_siteMap from "../schema/siteMap.js";
import type * as schema_smsOptOuts from "../schema/smsOptOuts.js";
import type * as schema_smsUsage from "../schema/smsUsage.js";
import type * as schema_songs from "../schema/songs.js";
import type * as schema_sponsorships from "../schema/sponsorships.js";
import type * as schema_templates from "../schema/templates.js";
import type * as schema_territories from "../schema/territories.js";
import type * as schema_ticketing from "../schema/ticketing.js";
import type * as seatProposals from "../seatProposals.js";
import type * as seatStructure from "../seatStructure.js";
import type * as seats from "../seats.js";
import type * as seed from "../seed.js";
import type * as seedTicketing from "../seedTicketing.js";
import type * as septemberAndCashApp from "../septemberAndCashApp.js";
import type * as serviceOptions from "../serviceOptions.js";
import type * as setlists from "../setlists.js";
import type * as siteMap from "../siteMap.js";
import type * as smsOptOuts from "../smsOptOuts.js";
import type * as smsReceipts from "../smsReceipts.js";
import type * as smsUsage from "../smsUsage.js";
import type * as songs from "../songs.js";
import type * as specializedRoles from "../specializedRoles.js";
import type * as sponsorships from "../sponsorships.js";
import type * as storage from "../storage.js";
import type * as stripe from "../stripe.js";
import type * as stripeFinance from "../stripeFinance.js";
import type * as templatePeople from "../templatePeople.js";
import type * as templateSync from "../templateSync.js";
import type * as templates from "../templates.js";
import type * as territories from "../territories.js";
import type * as ticketing from "../ticketing.js";
import type * as ticketingCountersBackfill from "../ticketingCountersBackfill.js";
import type * as ticketingEmails from "../ticketingEmails.js";
import type * as ticketingSms from "../ticketingSms.js";
import type * as ticketingVerification from "../ticketingVerification.js";
import type * as transactionCodings from "../transactionCodings.js";
import type * as transfers from "../transfers.js";
import type * as webhooks from "../webhooks.js";
import type * as work from "../work.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  academy: typeof academy;
  accessAllowlist: typeof accessAllowlist;
  ai: typeof ai;
  aiActions: typeof aiActions;
  aiEngine: typeof aiEngine;
  audiences: typeof audiences;
  auth: typeof auth;
  backerMilestones: typeof backerMilestones;
  blasts: typeof blasts;
  budgetDecisionEmails: typeof budgetDecisionEmails;
  budgetDetail: typeof budgetDetail;
  budgetLines: typeof budgetLines;
  campaignApprovalEmails: typeof campaignApprovalEmails;
  campaignPolls: typeof campaignPolls;
  campaignTemplates: typeof campaignTemplates;
  campaigns: typeof campaigns;
  cards: typeof cards;
  cashAppBackfill: typeof cashAppBackfill;
  checkIns: typeof checkIns;
  columns: typeof columns;
  commsSend: typeof commsSend;
  crons: typeof crons;
  dashboard: typeof dashboard;
  dashboardCharts: typeof dashboardCharts;
  dashboardDrill: typeof dashboardDrill;
  dataExports: typeof dataExports;
  dataHygiene: typeof dataHygiene;
  docs: typeof docs;
  donorIdentityBackfill: typeof donorIdentityBackfill;
  doorAccess: typeof doorAccess;
  emailHtmlImport: typeof emailHtmlImport;
  emailImages: typeof emailImages;
  emailPreview: typeof emailPreview;
  emailSuppressions: typeof emailSuppressions;
  emailThemes: typeof emailThemes;
  engagements: typeof engagements;
  eventAttendanceImport: typeof eventAttendanceImport;
  eventTypes: typeof eventTypes;
  events: typeof events;
  financeGenesisBackfill: typeof financeGenesisBackfill;
  financeRoles: typeof financeRoles;
  financeSettings: typeof financeSettings;
  finances: typeof finances;
  formSubmissions: typeof formSubmissions;
  gear2024Split: typeof gear2024Split;
  genesisApproveExceptions: typeof genesisApproveExceptions;
  genesisCleanup: typeof genesisCleanup;
  genesisDedupe: typeof genesisDedupe;
  genesisGiftSync: typeof genesisGiftSync;
  genesisRevenueSync: typeof genesisRevenueSync;
  givebutterRepair: typeof givebutterRepair;
  givebutterSync: typeof givebutterSync;
  giving: typeof giving;
  givingActivity: typeof givingActivity;
  givingCandidates: typeof givingCandidates;
  givingDonations: typeof givingDonations;
  givingImport: typeof givingImport;
  givingInterest: typeof givingInterest;
  givingPlatform: typeof givingPlatform;
  givingPledges: typeof givingPledges;
  googleChatChannels: typeof googleChatChannels;
  guestTeams: typeof guestTeams;
  guests: typeof guests;
  historicalBackfill: typeof historicalBackfill;
  http: typeof http;
  identity: typeof identity;
  increase: typeof increase;
  increaseAccounts: typeof increaseAccounts;
  increaseCardArt: typeof increaseCardArt;
  increaseExternalAccounts: typeof increaseExternalAccounts;
  increaseLedger: typeof increaseLedger;
  increasePayouts: typeof increasePayouts;
  increaseProvision: typeof increaseProvision;
  integrationSettings: typeof integrationSettings;
  inventory: typeof inventory;
  items: typeof items;
  legacyCards: typeof legacyCards;
  "lib/access": typeof lib_access;
  "lib/aiEngine": typeof lib_aiEngine;
  "lib/assets": typeof lib_assets;
  "lib/audienceResolve": typeof lib_audienceResolve;
  "lib/audienceTargeting": typeof lib_audienceTargeting;
  "lib/bookBalance": typeof lib_bookBalance;
  "lib/builtInTemplates": typeof lib_builtInTemplates;
  "lib/campaignKind": typeof lib_campaignKind;
  "lib/campaignsAccess": typeof lib_campaignsAccess;
  "lib/centralReach": typeof lib_centralReach;
  "lib/chapters": typeof lib_chapters;
  "lib/codingReminders": typeof lib_codingReminders;
  "lib/commsAccess": typeof lib_commsAccess;
  "lib/context": typeof lib_context;
  "lib/dataExportAccess": typeof lib_dataExportAccess;
  "lib/donorIdentity": typeof lib_donorIdentity;
  "lib/emailCodes": typeof lib_emailCodes;
  "lib/emailHtmlSanitize": typeof lib_emailHtmlSanitize;
  "lib/emailShell": typeof lib_emailShell;
  "lib/emlMessage": typeof lib_emlMessage;
  "lib/exportBuilders/academy": typeof lib_exportBuilders_academy;
  "lib/exportBuilders/eventsAndParticipation": typeof lib_exportBuilders_eventsAndParticipation;
  "lib/exportBuilders/finance": typeof lib_exportBuilders_finance;
  "lib/exportBuilders/formSubmissions": typeof lib_exportBuilders_formSubmissions;
  "lib/exportBuilders/giving": typeof lib_exportBuilders_giving;
  "lib/exportBuilders/index": typeof lib_exportBuilders_index;
  "lib/exportBuilders/people": typeof lib_exportBuilders_people;
  "lib/exportBuilders/types": typeof lib_exportBuilders_types;
  "lib/exportBuilders/work": typeof lib_exportBuilders_work;
  "lib/exportRunner": typeof lib_exportRunner;
  "lib/finance": typeof lib_finance;
  "lib/financeAuditLog": typeof lib_financeAuditLog;
  "lib/financeEditAccess": typeof lib_financeEditAccess;
  "lib/forPickerCandidates": typeof lib_forPickerCandidates;
  "lib/formCatalog": typeof lib_formCatalog;
  "lib/formsAccess": typeof lib_formsAccess;
  "lib/giftAudit": typeof lib_giftAudit;
  "lib/giveApiRoutes": typeof lib_giveApiRoutes;
  "lib/givePage": typeof lib_givePage;
  "lib/givePageClient": typeof lib_givePageClient;
  "lib/givePageSections": typeof lib_givePageSections;
  "lib/givePageStyles": typeof lib_givePageStyles;
  "lib/givingAccess": typeof lib_givingAccess;
  "lib/givingAudit": typeof lib_givingAudit;
  "lib/givingDonors": typeof lib_givingDonors;
  "lib/googleChat": typeof lib_googleChat;
  "lib/guestTeams": typeof lib_guestTeams;
  "lib/guides": typeof lib_guides;
  "lib/html": typeof lib_html;
  "lib/identityAccess": typeof lib_identityAccess;
  "lib/identityEvidence": typeof lib_identityEvidence;
  "lib/imageSniff": typeof lib_imageSniff;
  "lib/increaseApi": typeof lib_increaseApi;
  "lib/increaseExtract": typeof lib_increaseExtract;
  "lib/increaseFiles": typeof lib_increaseFiles;
  "lib/increasePayoutMachine": typeof lib_increasePayoutMachine;
  "lib/increaseShapes": typeof lib_increaseShapes;
  "lib/landingPage": typeof lib_landingPage;
  "lib/landingPageClient": typeof lib_landingPageClient;
  "lib/landingPageStyles": typeof lib_landingPageStyles;
  "lib/landingPageVerifyClient": typeof lib_landingPageVerifyClient;
  "lib/merchantSimilarity": typeof lib_merchantSimilarity;
  "lib/org": typeof lib_org;
  "lib/people": typeof lib_people;
  "lib/peopleAggregate": typeof lib_peopleAggregate;
  "lib/personEmails": typeof lib_personEmails;
  "lib/personName": typeof lib_personName;
  "lib/phoneCodes": typeof lib_phoneCodes;
  "lib/placements": typeof lib_placements;
  "lib/platformGuides": typeof lib_platformGuides;
  "lib/pollPage": typeof lib_pollPage;
  "lib/projectActionPage": typeof lib_projectActionPage;
  "lib/publishabilityAccess": typeof lib_publishabilityAccess;
  "lib/readiness": typeof lib_readiness;
  "lib/receiptExceptionAccess": typeof lib_receiptExceptionAccess;
  "lib/receiptExceptions": typeof lib_receiptExceptions;
  "lib/receiptLinks": typeof lib_receiptLinks;
  "lib/receiptRetry": typeof lib_receiptRetry;
  "lib/receiptSuggestionAccess": typeof lib_receiptSuggestionAccess;
  "lib/reconciliationAccess": typeof lib_reconciliationAccess;
  "lib/reconciliationGap": typeof lib_reconciliationGap;
  "lib/reimburseApiRoutes": typeof lib_reimburseApiRoutes;
  "lib/reimbursePage": typeof lib_reimbursePage;
  "lib/reimbursementTxnFields": typeof lib_reimbursementTxnFields;
  "lib/resend": typeof lib_resend;
  "lib/rsvpPeople": typeof lib_rsvpPeople;
  "lib/salesCatalog": typeof lib_salesCatalog;
  "lib/seatStructure": typeof lib_seatStructure;
  "lib/seats": typeof lib_seats;
  "lib/seed/fieldDay": typeof lib_seed_fieldDay;
  "lib/seed/finance": typeof lib_seed_finance;
  "lib/seed/helpers": typeof lib_seed_helpers;
  "lib/seed/historical/cashApp2026": typeof lib_seed_historical_cashApp2026;
  "lib/seed/historical/eden": typeof lib_seed_historical_eden;
  "lib/seed/historical/fieldDayTickets": typeof lib_seed_historical_fieldDayTickets;
  "lib/seed/historical/gear2024Orders": typeof lib_seed_historical_gear2024Orders;
  "lib/seed/historical/genesis": typeof lib_seed_historical_genesis;
  "lib/seed/historical/genesisBank": typeof lib_seed_historical_genesisBank;
  "lib/seed/historical/genesisCleanup2026": typeof lib_seed_historical_genesisCleanup2026;
  "lib/seed/historical/genesisDedupe2026": typeof lib_seed_historical_genesisDedupe2026;
  "lib/seed/historical/genesisInkindExpenses": typeof lib_seed_historical_genesisInkindExpenses;
  "lib/seed/historical/genesisLtn": typeof lib_seed_historical_genesisLtn;
  "lib/seed/historical/givebutterRepair2026": typeof lib_seed_historical_givebutterRepair2026;
  "lib/seed/historical/giving": typeof lib_seed_historical_giving;
  "lib/seed/historical/ltn": typeof lib_seed_historical_ltn;
  "lib/seed/historical/mapping": typeof lib_seed_historical_mapping;
  "lib/seed/historical/nye": typeof lib_seed_historical_nye;
  "lib/seed/historical/ptb": typeof lib_seed_historical_ptb;
  "lib/seed/historical/ptbGbTickets": typeof lib_seed_historical_ptbGbTickets;
  "lib/seed/historical/ptbVenmo2026": typeof lib_seed_historical_ptbVenmo2026;
  "lib/seed/historical/types": typeof lib_seed_historical_types;
  "lib/seed/loveThyNeighbor": typeof lib_seed_loveThyNeighbor;
  "lib/seed/roster": typeof lib_seed_roster;
  "lib/seed/templates": typeof lib_seed_templates;
  "lib/serviceCatalog": typeof lib_serviceCatalog;
  "lib/servicesAccess": typeof lib_servicesAccess;
  "lib/sha256": typeof lib_sha256;
  "lib/siteUrl": typeof lib_siteUrl;
  "lib/ssrfGuard": typeof lib_ssrfGuard;
  "lib/standardWebhook": typeof lib_standardWebhook;
  "lib/superuser": typeof lib_superuser;
  "lib/templates": typeof lib_templates;
  "lib/ticketApiRoutes": typeof lib_ticketApiRoutes;
  "lib/ticketingAccess": typeof lib_ticketingAccess;
  "lib/tiptapCampaignRender": typeof lib_tiptapCampaignRender;
  "lib/transactionCoding": typeof lib_transactionCoding;
  "lib/transactionCodingAccess": typeof lib_transactionCodingAccess;
  "lib/transferPair": typeof lib_transferPair;
  "lib/twilio": typeof lib_twilio;
  "lib/unsubscribePage": typeof lib_unsubscribePage;
  linkTruistGifts: typeof linkTruistGifts;
  maintenance: typeof maintenance;
  markPtbPayout: typeof markPtbPayout;
  migrations: typeof migrations;
  "migrations/0000_seed_ledger": typeof migrations_0000_seed_ledger;
  "migrations/0007_cleanup_renamed_guide_slugs": typeof migrations_0007_cleanup_renamed_guide_slugs;
  "migrations/0008_cleanup_orphaned_placements": typeof migrations_0008_cleanup_orphaned_placements;
  "migrations/0009_backfill_people_services": typeof migrations_0009_backfill_people_services;
  "migrations/0010_backfill_template_people_teams": typeof migrations_0010_backfill_template_people_teams;
  "migrations/0011_backfill_person_status": typeof migrations_0011_backfill_person_status;
  "migrations/0012_materialize_how_to_docs": typeof migrations_0012_materialize_how_to_docs;
  "migrations/0013_fold_project_status_notes": typeof migrations_0013_fold_project_status_notes;
  "migrations/0014_copy_guest_allowlist": typeof migrations_0014_copy_guest_allowlist;
  "migrations/0015_audit_column_types": typeof migrations_0015_audit_column_types;
  "migrations/0016_clear_legacy_fields": typeof migrations_0016_clear_legacy_fields;
  "migrations/0017_purge_guest_allowlist": typeof migrations_0017_purge_guest_allowlist;
  "migrations/0018_backfill_course_completions": typeof migrations_0018_backfill_course_completions;
  "migrations/0019_backfill_run_of_show_duration": typeof migrations_0019_backfill_run_of_show_duration;
  "migrations/0020_permits_states_and_fallback": typeof migrations_0020_permits_states_and_fallback;
  "migrations/0021_inventory_category_to_tags": typeof migrations_0021_inventory_category_to_tags;
  "migrations/0022_seed_seat_defs": typeof migrations_0022_seed_seat_defs;
  "migrations/0023_seed_seat_assignments": typeof migrations_0023_seed_seat_assignments;
  "migrations/0024_repoint_derived_seat_duties": typeof migrations_0024_repoint_derived_seat_duties;
  "migrations/0025_add_cd_finance_viewer": typeof migrations_0025_add_cd_finance_viewer;
  "migrations/0026_migrate_budget_v1_lines": typeof migrations_0026_migrate_budget_v1_lines;
  "migrations/0027_sync_linked_budget_identity": typeof migrations_0027_sync_linked_budget_identity;
  "migrations/0028_reaward_course_completions": typeof migrations_0028_reaward_course_completions;
  "migrations/0029_territories_cutover": typeof migrations_0029_territories_cutover;
  "migrations/0030_backfill_launch_fund": typeof migrations_0030_backfill_launch_fund;
  "migrations/0031_gift_method_sources": typeof migrations_0031_gift_method_sources;
  "migrations/0032_link_donor_people": typeof migrations_0032_link_donor_people;
  "migrations/0033_add_giving_power_defaults": typeof migrations_0033_add_giving_power_defaults;
  "migrations/0034_merge_duplicate_gb_guests": typeof migrations_0034_merge_duplicate_gb_guests;
  "migrations/0035_backfill_receipt_documents": typeof migrations_0035_backfill_receipt_documents;
  "migrations/0036_add_campaign_power_defaults": typeof migrations_0036_add_campaign_power_defaults;
  "migrations/0037_link_rsvp_people": typeof migrations_0037_link_rsvp_people;
  "migrations/0038_backfill_contact_only_people": typeof migrations_0038_backfill_contact_only_people;
  "migrations/0039_backfill_person_emails": typeof migrations_0039_backfill_person_emails;
  "migrations/0040_migrate_legacy_audiences": typeof migrations_0040_migrate_legacy_audiences;
  "migrations/0041_migrate_guest_audiences": typeof migrations_0041_migrate_guest_audiences;
  "migrations/0042_wrap_targeting": typeof migrations_0042_wrap_targeting;
  "migrations/0043_split_person_names": typeof migrations_0043_split_person_names;
  "migrations/0044_reimbursement_payouts_outflow": typeof migrations_0044_reimbursement_payouts_outflow;
  "migrations/0045_backfill_personal_repayments": typeof migrations_0045_backfill_personal_repayments;
  "migrations/0046_seed_service_catalog": typeof migrations_0046_seed_service_catalog;
  "migrations/0047_service_conditions_to_ids": typeof migrations_0047_service_conditions_to_ids;
  "migrations/0048_import_form_submissions": typeof migrations_0048_import_form_submissions;
  "migrations/0049_seed_builtin_campaign_templates": typeof migrations_0049_seed_builtin_campaign_templates;
  "migrations/0050_link_rsvp_identifiers": typeof migrations_0050_link_rsvp_identifiers;
  "migrations/0051_backfill_people_persona": typeof migrations_0051_backfill_people_persona;
  "migrations/0052_import_newsletter_images": typeof migrations_0052_import_newsletter_images;
  "migrations/0053_add_campaign_design_defaults": typeof migrations_0053_add_campaign_design_defaults;
  "migrations/0054_seed_org_mailing_address": typeof migrations_0054_seed_org_mailing_address;
  "migrations/0055_merge_campaign_templates_into_campaigns": typeof migrations_0055_merge_campaign_templates_into_campaigns;
  "migrations/0056_upgrade_builtin_newsletter_tiptap": typeof migrations_0056_upgrade_builtin_newsletter_tiptap;
  "migrations/0057_backfill_increase_transactions": typeof migrations_0057_backfill_increase_transactions;
  "migrations/0058_add_data_export_defaults": typeof migrations_0058_add_data_export_defaults;
  "migrations/0059_split_legacy_increase_cards": typeof migrations_0059_split_legacy_increase_cards;
  "migrations/0060_add_events_checkin_defaults": typeof migrations_0060_add_events_checkin_defaults;
  "migrations/index": typeof migrations_index;
  modules: typeof modules;
  moneyViews: typeof moneyViews;
  netOutCashGifts: typeof netOutCashGifts;
  oneoffDedupeRelay: typeof oneoffDedupeRelay;
  org: typeof org;
  people: typeof people;
  peopleImport: typeof peopleImport;
  personEmails: typeof personEmails;
  places: typeof places;
  processorFees: typeof processorFees;
  profiles: typeof profiles;
  projectActions: typeof projectActions;
  projects: typeof projects;
  ptbVenmoBackfill: typeof ptbVenmoBackfill;
  publishability: typeof publishability;
  receiptExceptions: typeof receiptExceptions;
  receiptInbox: typeof receiptInbox;
  receiptInboxBackfill: typeof receiptInboxBackfill;
  receiptPdf: typeof receiptPdf;
  receipts: typeof receipts;
  reconcileSuggest: typeof reconcileSuggest;
  reconciliation: typeof reconciliation;
  reimbursementBackfill: typeof reimbursementBackfill;
  reimbursements: typeof reimbursements;
  reminders: typeof reminders;
  responsibilities: typeof responsibilities;
  restoreTruistDeposit: typeof restoreTruistDeposit;
  reverseBadSettlement: typeof reverseBadSettlement;
  roleAssignments: typeof roleAssignments;
  roles: typeof roles;
  sales: typeof sales;
  salesSync: typeof salesSync;
  "schema/academy": typeof schema_academy;
  "schema/accessAllowlist": typeof schema_accessAllowlist;
  "schema/ai": typeof schema_ai;
  "schema/backerMilestones": typeof schema_backerMilestones;
  "schema/campaigns": typeof schema_campaigns;
  "schema/chapters": typeof schema_chapters;
  "schema/dataExports": typeof schema_dataExports;
  "schema/docs": typeof schema_docs;
  "schema/events": typeof schema_events;
  "schema/finances": typeof schema_finances;
  "schema/forms": typeof schema_forms;
  "schema/givingActivity": typeof schema_givingActivity;
  "schema/givingInterest": typeof schema_givingInterest;
  "schema/givingPlatform": typeof schema_givingPlatform;
  "schema/googleChatChannels": typeof schema_googleChatChannels;
  "schema/identity": typeof schema_identity;
  "schema/integrationSettings": typeof schema_integrationSettings;
  "schema/inventory": typeof schema_inventory;
  "schema/migrations": typeof schema_migrations;
  "schema/modules": typeof schema_modules;
  "schema/people": typeof schema_people;
  "schema/projects": typeof schema_projects;
  "schema/responsibilities": typeof schema_responsibilities;
  "schema/roles": typeof schema_roles;
  "schema/seatProposals": typeof schema_seatProposals;
  "schema/seatStructureLog": typeof schema_seatStructureLog;
  "schema/seats": typeof schema_seats;
  "schema/services": typeof schema_services;
  "schema/shared": typeof schema_shared;
  "schema/siteMap": typeof schema_siteMap;
  "schema/smsOptOuts": typeof schema_smsOptOuts;
  "schema/smsUsage": typeof schema_smsUsage;
  "schema/songs": typeof schema_songs;
  "schema/sponsorships": typeof schema_sponsorships;
  "schema/templates": typeof schema_templates;
  "schema/territories": typeof schema_territories;
  "schema/ticketing": typeof schema_ticketing;
  seatProposals: typeof seatProposals;
  seatStructure: typeof seatStructure;
  seats: typeof seats;
  seed: typeof seed;
  seedTicketing: typeof seedTicketing;
  septemberAndCashApp: typeof septemberAndCashApp;
  serviceOptions: typeof serviceOptions;
  setlists: typeof setlists;
  siteMap: typeof siteMap;
  smsOptOuts: typeof smsOptOuts;
  smsReceipts: typeof smsReceipts;
  smsUsage: typeof smsUsage;
  songs: typeof songs;
  specializedRoles: typeof specializedRoles;
  sponsorships: typeof sponsorships;
  storage: typeof storage;
  stripe: typeof stripe;
  stripeFinance: typeof stripeFinance;
  templatePeople: typeof templatePeople;
  templateSync: typeof templateSync;
  templates: typeof templates;
  territories: typeof territories;
  ticketing: typeof ticketing;
  ticketingCountersBackfill: typeof ticketingCountersBackfill;
  ticketingEmails: typeof ticketingEmails;
  ticketingSms: typeof ticketingSms;
  ticketingVerification: typeof ticketingVerification;
  transactionCodings: typeof transactionCodings;
  transfers: typeof transfers;
  webhooks: typeof webhooks;
  work: typeof work;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  peopleByPersona: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"peopleByPersona">;
};
