/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as academy from "../academy.js";
import type * as accessAllowlist from "../accessAllowlist.js";
import type * as ai from "../ai.js";
import type * as aiActions from "../aiActions.js";
import type * as aiCoding from "../aiCoding.js";
import type * as aiCodingData from "../aiCodingData.js";
import type * as auth from "../auth.js";
import type * as backerMilestones from "../backerMilestones.js";
import type * as blasts from "../blasts.js";
import type * as budgetLines from "../budgetLines.js";
import type * as cards from "../cards.js";
import type * as checkIns from "../checkIns.js";
import type * as columns from "../columns.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboardCharts from "../dashboardCharts.js";
import type * as dashboardDrill from "../dashboardDrill.js";
import type * as dataHygiene from "../dataHygiene.js";
import type * as docs from "../docs.js";
import type * as engagements from "../engagements.js";
import type * as eventAttendanceImport from "../eventAttendanceImport.js";
import type * as eventTypes from "../eventTypes.js";
import type * as events from "../events.js";
import type * as financeGenesisBackfill from "../financeGenesisBackfill.js";
import type * as financeRoles from "../financeRoles.js";
import type * as financeSettings from "../financeSettings.js";
import type * as finances from "../finances.js";
import type * as givebutterSync from "../givebutterSync.js";
import type * as giving from "../giving.js";
import type * as givingCandidates from "../givingCandidates.js";
import type * as givingDonations from "../givingDonations.js";
import type * as givingImport from "../givingImport.js";
import type * as givingInterest from "../givingInterest.js";
import type * as givingPlatform from "../givingPlatform.js";
import type * as givingPledges from "../givingPledges.js";
import type * as guests from "../guests.js";
import type * as historicalBackfill from "../historicalBackfill.js";
import type * as http from "../http.js";
import type * as increase from "../increase.js";
import type * as integrationSettings from "../integrationSettings.js";
import type * as inventory from "../inventory.js";
import type * as items from "../items.js";
import type * as legacyCards from "../legacyCards.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_assets from "../lib/assets.js";
import type * as lib_centralReach from "../lib/centralReach.js";
import type * as lib_chapters from "../lib/chapters.js";
import type * as lib_context from "../lib/context.js";
import type * as lib_emailCodes from "../lib/emailCodes.js";
import type * as lib_finance from "../lib/finance.js";
import type * as lib_forPickerCandidates from "../lib/forPickerCandidates.js";
import type * as lib_giftAudit from "../lib/giftAudit.js";
import type * as lib_giveApiRoutes from "../lib/giveApiRoutes.js";
import type * as lib_givePage from "../lib/givePage.js";
import type * as lib_givePageClient from "../lib/givePageClient.js";
import type * as lib_givePageStyles from "../lib/givePageStyles.js";
import type * as lib_givingAccess from "../lib/givingAccess.js";
import type * as lib_givingAudit from "../lib/givingAudit.js";
import type * as lib_givingDonors from "../lib/givingDonors.js";
import type * as lib_guides from "../lib/guides.js";
import type * as lib_html from "../lib/html.js";
import type * as lib_landingPage from "../lib/landingPage.js";
import type * as lib_landingPageClient from "../lib/landingPageClient.js";
import type * as lib_landingPageStyles from "../lib/landingPageStyles.js";
import type * as lib_landingPageVerifyClient from "../lib/landingPageVerifyClient.js";
import type * as lib_org from "../lib/org.js";
import type * as lib_people from "../lib/people.js";
import type * as lib_phoneCodes from "../lib/phoneCodes.js";
import type * as lib_placements from "../lib/placements.js";
import type * as lib_platformGuides from "../lib/platformGuides.js";
import type * as lib_projectActionPage from "../lib/projectActionPage.js";
import type * as lib_readiness from "../lib/readiness.js";
import type * as lib_reimburseApiRoutes from "../lib/reimburseApiRoutes.js";
import type * as lib_reimbursePage from "../lib/reimbursePage.js";
import type * as lib_seatStructure from "../lib/seatStructure.js";
import type * as lib_seats from "../lib/seats.js";
import type * as lib_seed_fieldDay from "../lib/seed/fieldDay.js";
import type * as lib_seed_finance from "../lib/seed/finance.js";
import type * as lib_seed_helpers from "../lib/seed/helpers.js";
import type * as lib_seed_historical_eden from "../lib/seed/historical/eden.js";
import type * as lib_seed_historical_fieldDayTickets from "../lib/seed/historical/fieldDayTickets.js";
import type * as lib_seed_historical_genesis from "../lib/seed/historical/genesis.js";
import type * as lib_seed_historical_genesisBank from "../lib/seed/historical/genesisBank.js";
import type * as lib_seed_historical_genesisInkindExpenses from "../lib/seed/historical/genesisInkindExpenses.js";
import type * as lib_seed_historical_genesisLtn from "../lib/seed/historical/genesisLtn.js";
import type * as lib_seed_historical_giving from "../lib/seed/historical/giving.js";
import type * as lib_seed_historical_ltn from "../lib/seed/historical/ltn.js";
import type * as lib_seed_historical_mapping from "../lib/seed/historical/mapping.js";
import type * as lib_seed_historical_nye from "../lib/seed/historical/nye.js";
import type * as lib_seed_historical_ptb from "../lib/seed/historical/ptb.js";
import type * as lib_seed_historical_ptbGbTickets from "../lib/seed/historical/ptbGbTickets.js";
import type * as lib_seed_historical_types from "../lib/seed/historical/types.js";
import type * as lib_seed_roster from "../lib/seed/roster.js";
import type * as lib_seed_templates from "../lib/seed/templates.js";
import type * as lib_sha256 from "../lib/sha256.js";
import type * as lib_siteUrl from "../lib/siteUrl.js";
import type * as lib_superuser from "../lib/superuser.js";
import type * as lib_templates from "../lib/templates.js";
import type * as lib_ticketApiRoutes from "../lib/ticketApiRoutes.js";
import type * as lib_twilio from "../lib/twilio.js";
import type * as maintenance from "../maintenance.js";
import type * as migrations from "../migrations.js";
import type * as migrations_0000_seed_ledger from "../migrations/0000_seed_ledger.js";
import type * as migrations_0007_cleanup_renamed_guide_slugs from "../migrations/0007_cleanup_renamed_guide_slugs.js";
import type * as migrations_0008_cleanup_orphaned_placements from "../migrations/0008_cleanup_orphaned_placements.js";
import type * as migrations_0009_backfill_people_services from "../migrations/0009_backfill_people_services.js";
import type * as migrations_0010_backfill_template_people_teams from "../migrations/0010_backfill_template_people_teams.js";
import type * as migrations_0011_backfill_person_status from "../migrations/0011_backfill_person_status.js";
import type * as migrations_0012_materialize_how_to_docs from "../migrations/0012_materialize_how_to_docs.js";
import type * as migrations_0013_fold_project_status_notes from "../migrations/0013_fold_project_status_notes.js";
import type * as migrations_0014_copy_guest_allowlist from "../migrations/0014_copy_guest_allowlist.js";
import type * as migrations_0015_audit_column_types from "../migrations/0015_audit_column_types.js";
import type * as migrations_0016_clear_legacy_fields from "../migrations/0016_clear_legacy_fields.js";
import type * as migrations_0017_purge_guest_allowlist from "../migrations/0017_purge_guest_allowlist.js";
import type * as migrations_0018_backfill_course_completions from "../migrations/0018_backfill_course_completions.js";
import type * as migrations_0019_backfill_run_of_show_duration from "../migrations/0019_backfill_run_of_show_duration.js";
import type * as migrations_0020_permits_states_and_fallback from "../migrations/0020_permits_states_and_fallback.js";
import type * as migrations_0021_inventory_category_to_tags from "../migrations/0021_inventory_category_to_tags.js";
import type * as migrations_0022_seed_seat_defs from "../migrations/0022_seed_seat_defs.js";
import type * as migrations_0023_seed_seat_assignments from "../migrations/0023_seed_seat_assignments.js";
import type * as migrations_0024_repoint_derived_seat_duties from "../migrations/0024_repoint_derived_seat_duties.js";
import type * as migrations_0025_add_cd_finance_viewer from "../migrations/0025_add_cd_finance_viewer.js";
import type * as migrations_0026_migrate_budget_v1_lines from "../migrations/0026_migrate_budget_v1_lines.js";
import type * as migrations_0027_sync_linked_budget_identity from "../migrations/0027_sync_linked_budget_identity.js";
import type * as migrations_0028_reaward_course_completions from "../migrations/0028_reaward_course_completions.js";
import type * as migrations_0029_territories_cutover from "../migrations/0029_territories_cutover.js";
import type * as migrations_0030_backfill_launch_fund from "../migrations/0030_backfill_launch_fund.js";
import type * as migrations_0031_gift_method_sources from "../migrations/0031_gift_method_sources.js";
import type * as migrations_0032_link_donor_people from "../migrations/0032_link_donor_people.js";
import type * as migrations_0033_add_giving_power_defaults from "../migrations/0033_add_giving_power_defaults.js";
import type * as migrations_0034_merge_duplicate_gb_guests from "../migrations/0034_merge_duplicate_gb_guests.js";
import type * as migrations_index from "../migrations/index.js";
import type * as modules from "../modules.js";
import type * as moneyViews from "../moneyViews.js";
import type * as oneoffDedupeRelay from "../oneoffDedupeRelay.js";
import type * as org from "../org.js";
import type * as people from "../people.js";
import type * as places from "../places.js";
import type * as profiles from "../profiles.js";
import type * as projectActions from "../projectActions.js";
import type * as projects from "../projects.js";
import type * as reconcileSuggest from "../reconcileSuggest.js";
import type * as reimbursements from "../reimbursements.js";
import type * as reminders from "../reminders.js";
import type * as responsibilities from "../responsibilities.js";
import type * as roleAssignments from "../roleAssignments.js";
import type * as roles from "../roles.js";
import type * as schema_academy from "../schema/academy.js";
import type * as schema_accessAllowlist from "../schema/accessAllowlist.js";
import type * as schema_ai from "../schema/ai.js";
import type * as schema_aiUsage from "../schema/aiUsage.js";
import type * as schema_backerMilestones from "../schema/backerMilestones.js";
import type * as schema_chapters from "../schema/chapters.js";
import type * as schema_docs from "../schema/docs.js";
import type * as schema_events from "../schema/events.js";
import type * as schema_finances from "../schema/finances.js";
import type * as schema_givingInterest from "../schema/givingInterest.js";
import type * as schema_givingPlatform from "../schema/givingPlatform.js";
import type * as schema_integrationSettings from "../schema/integrationSettings.js";
import type * as schema_inventory from "../schema/inventory.js";
import type * as schema_migrations from "../schema/migrations.js";
import type * as schema_modules from "../schema/modules.js";
import type * as schema_people from "../schema/people.js";
import type * as schema_projects from "../schema/projects.js";
import type * as schema_responsibilities from "../schema/responsibilities.js";
import type * as schema_roles from "../schema/roles.js";
import type * as schema_seatProposals from "../schema/seatProposals.js";
import type * as schema_seatStructureLog from "../schema/seatStructureLog.js";
import type * as schema_seats from "../schema/seats.js";
import type * as schema_shared from "../schema/shared.js";
import type * as schema_siteMap from "../schema/siteMap.js";
import type * as schema_songs from "../schema/songs.js";
import type * as schema_sponsorships from "../schema/sponsorships.js";
import type * as schema_templates from "../schema/templates.js";
import type * as schema_territories from "../schema/territories.js";
import type * as schema_ticketing from "../schema/ticketing.js";
import type * as seatProposals from "../seatProposals.js";
import type * as seatStructure from "../seatStructure.js";
import type * as seats from "../seats.js";
import type * as seed from "../seed.js";
import type * as seedTicketing from "../seedTicketing.js";
import type * as setlists from "../setlists.js";
import type * as siteMap from "../siteMap.js";
import type * as songs from "../songs.js";
import type * as specializedRoles from "../specializedRoles.js";
import type * as sponsorships from "../sponsorships.js";
import type * as storage from "../storage.js";
import type * as stripe from "../stripe.js";
import type * as stripeFinance from "../stripeFinance.js";
import type * as templatePeople from "../templatePeople.js";
import type * as templateSync from "../templateSync.js";
import type * as templates from "../templates.js";
import type * as territories from "../territories.js";
import type * as ticketing from "../ticketing.js";
import type * as ticketingEmails from "../ticketingEmails.js";
import type * as ticketingSms from "../ticketingSms.js";
import type * as ticketingVerification from "../ticketingVerification.js";
import type * as transfers from "../transfers.js";
import type * as webhooks from "../webhooks.js";
import type * as work from "../work.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  academy: typeof academy;
  accessAllowlist: typeof accessAllowlist;
  ai: typeof ai;
  aiActions: typeof aiActions;
  aiCoding: typeof aiCoding;
  aiCodingData: typeof aiCodingData;
  auth: typeof auth;
  backerMilestones: typeof backerMilestones;
  blasts: typeof blasts;
  budgetLines: typeof budgetLines;
  cards: typeof cards;
  checkIns: typeof checkIns;
  columns: typeof columns;
  crons: typeof crons;
  dashboard: typeof dashboard;
  dashboardCharts: typeof dashboardCharts;
  dashboardDrill: typeof dashboardDrill;
  dataHygiene: typeof dataHygiene;
  docs: typeof docs;
  engagements: typeof engagements;
  eventAttendanceImport: typeof eventAttendanceImport;
  eventTypes: typeof eventTypes;
  events: typeof events;
  financeGenesisBackfill: typeof financeGenesisBackfill;
  financeRoles: typeof financeRoles;
  financeSettings: typeof financeSettings;
  finances: typeof finances;
  givebutterSync: typeof givebutterSync;
  giving: typeof giving;
  givingCandidates: typeof givingCandidates;
  givingDonations: typeof givingDonations;
  givingImport: typeof givingImport;
  givingInterest: typeof givingInterest;
  givingPlatform: typeof givingPlatform;
  givingPledges: typeof givingPledges;
  guests: typeof guests;
  historicalBackfill: typeof historicalBackfill;
  http: typeof http;
  increase: typeof increase;
  integrationSettings: typeof integrationSettings;
  inventory: typeof inventory;
  items: typeof items;
  legacyCards: typeof legacyCards;
  "lib/access": typeof lib_access;
  "lib/assets": typeof lib_assets;
  "lib/centralReach": typeof lib_centralReach;
  "lib/chapters": typeof lib_chapters;
  "lib/context": typeof lib_context;
  "lib/emailCodes": typeof lib_emailCodes;
  "lib/finance": typeof lib_finance;
  "lib/forPickerCandidates": typeof lib_forPickerCandidates;
  "lib/giftAudit": typeof lib_giftAudit;
  "lib/giveApiRoutes": typeof lib_giveApiRoutes;
  "lib/givePage": typeof lib_givePage;
  "lib/givePageClient": typeof lib_givePageClient;
  "lib/givePageStyles": typeof lib_givePageStyles;
  "lib/givingAccess": typeof lib_givingAccess;
  "lib/givingAudit": typeof lib_givingAudit;
  "lib/givingDonors": typeof lib_givingDonors;
  "lib/guides": typeof lib_guides;
  "lib/html": typeof lib_html;
  "lib/landingPage": typeof lib_landingPage;
  "lib/landingPageClient": typeof lib_landingPageClient;
  "lib/landingPageStyles": typeof lib_landingPageStyles;
  "lib/landingPageVerifyClient": typeof lib_landingPageVerifyClient;
  "lib/org": typeof lib_org;
  "lib/people": typeof lib_people;
  "lib/phoneCodes": typeof lib_phoneCodes;
  "lib/placements": typeof lib_placements;
  "lib/platformGuides": typeof lib_platformGuides;
  "lib/projectActionPage": typeof lib_projectActionPage;
  "lib/readiness": typeof lib_readiness;
  "lib/reimburseApiRoutes": typeof lib_reimburseApiRoutes;
  "lib/reimbursePage": typeof lib_reimbursePage;
  "lib/seatStructure": typeof lib_seatStructure;
  "lib/seats": typeof lib_seats;
  "lib/seed/fieldDay": typeof lib_seed_fieldDay;
  "lib/seed/finance": typeof lib_seed_finance;
  "lib/seed/helpers": typeof lib_seed_helpers;
  "lib/seed/historical/eden": typeof lib_seed_historical_eden;
  "lib/seed/historical/fieldDayTickets": typeof lib_seed_historical_fieldDayTickets;
  "lib/seed/historical/genesis": typeof lib_seed_historical_genesis;
  "lib/seed/historical/genesisBank": typeof lib_seed_historical_genesisBank;
  "lib/seed/historical/genesisInkindExpenses": typeof lib_seed_historical_genesisInkindExpenses;
  "lib/seed/historical/genesisLtn": typeof lib_seed_historical_genesisLtn;
  "lib/seed/historical/giving": typeof lib_seed_historical_giving;
  "lib/seed/historical/ltn": typeof lib_seed_historical_ltn;
  "lib/seed/historical/mapping": typeof lib_seed_historical_mapping;
  "lib/seed/historical/nye": typeof lib_seed_historical_nye;
  "lib/seed/historical/ptb": typeof lib_seed_historical_ptb;
  "lib/seed/historical/ptbGbTickets": typeof lib_seed_historical_ptbGbTickets;
  "lib/seed/historical/types": typeof lib_seed_historical_types;
  "lib/seed/roster": typeof lib_seed_roster;
  "lib/seed/templates": typeof lib_seed_templates;
  "lib/sha256": typeof lib_sha256;
  "lib/siteUrl": typeof lib_siteUrl;
  "lib/superuser": typeof lib_superuser;
  "lib/templates": typeof lib_templates;
  "lib/ticketApiRoutes": typeof lib_ticketApiRoutes;
  "lib/twilio": typeof lib_twilio;
  maintenance: typeof maintenance;
  migrations: typeof migrations;
  "migrations/0000_seed_ledger": typeof migrations_0000_seed_ledger;
  "migrations/0007_cleanup_renamed_guide_slugs": typeof migrations_0007_cleanup_renamed_guide_slugs;
  "migrations/0008_cleanup_orphaned_placements": typeof migrations_0008_cleanup_orphaned_placements;
  "migrations/0009_backfill_people_services": typeof migrations_0009_backfill_people_services;
  "migrations/0010_backfill_template_people_teams": typeof migrations_0010_backfill_template_people_teams;
  "migrations/0011_backfill_person_status": typeof migrations_0011_backfill_person_status;
  "migrations/0012_materialize_how_to_docs": typeof migrations_0012_materialize_how_to_docs;
  "migrations/0013_fold_project_status_notes": typeof migrations_0013_fold_project_status_notes;
  "migrations/0014_copy_guest_allowlist": typeof migrations_0014_copy_guest_allowlist;
  "migrations/0015_audit_column_types": typeof migrations_0015_audit_column_types;
  "migrations/0016_clear_legacy_fields": typeof migrations_0016_clear_legacy_fields;
  "migrations/0017_purge_guest_allowlist": typeof migrations_0017_purge_guest_allowlist;
  "migrations/0018_backfill_course_completions": typeof migrations_0018_backfill_course_completions;
  "migrations/0019_backfill_run_of_show_duration": typeof migrations_0019_backfill_run_of_show_duration;
  "migrations/0020_permits_states_and_fallback": typeof migrations_0020_permits_states_and_fallback;
  "migrations/0021_inventory_category_to_tags": typeof migrations_0021_inventory_category_to_tags;
  "migrations/0022_seed_seat_defs": typeof migrations_0022_seed_seat_defs;
  "migrations/0023_seed_seat_assignments": typeof migrations_0023_seed_seat_assignments;
  "migrations/0024_repoint_derived_seat_duties": typeof migrations_0024_repoint_derived_seat_duties;
  "migrations/0025_add_cd_finance_viewer": typeof migrations_0025_add_cd_finance_viewer;
  "migrations/0026_migrate_budget_v1_lines": typeof migrations_0026_migrate_budget_v1_lines;
  "migrations/0027_sync_linked_budget_identity": typeof migrations_0027_sync_linked_budget_identity;
  "migrations/0028_reaward_course_completions": typeof migrations_0028_reaward_course_completions;
  "migrations/0029_territories_cutover": typeof migrations_0029_territories_cutover;
  "migrations/0030_backfill_launch_fund": typeof migrations_0030_backfill_launch_fund;
  "migrations/0031_gift_method_sources": typeof migrations_0031_gift_method_sources;
  "migrations/0032_link_donor_people": typeof migrations_0032_link_donor_people;
  "migrations/0033_add_giving_power_defaults": typeof migrations_0033_add_giving_power_defaults;
  "migrations/0034_merge_duplicate_gb_guests": typeof migrations_0034_merge_duplicate_gb_guests;
  "migrations/index": typeof migrations_index;
  modules: typeof modules;
  moneyViews: typeof moneyViews;
  oneoffDedupeRelay: typeof oneoffDedupeRelay;
  org: typeof org;
  people: typeof people;
  places: typeof places;
  profiles: typeof profiles;
  projectActions: typeof projectActions;
  projects: typeof projects;
  reconcileSuggest: typeof reconcileSuggest;
  reimbursements: typeof reimbursements;
  reminders: typeof reminders;
  responsibilities: typeof responsibilities;
  roleAssignments: typeof roleAssignments;
  roles: typeof roles;
  "schema/academy": typeof schema_academy;
  "schema/accessAllowlist": typeof schema_accessAllowlist;
  "schema/ai": typeof schema_ai;
  "schema/aiUsage": typeof schema_aiUsage;
  "schema/backerMilestones": typeof schema_backerMilestones;
  "schema/chapters": typeof schema_chapters;
  "schema/docs": typeof schema_docs;
  "schema/events": typeof schema_events;
  "schema/finances": typeof schema_finances;
  "schema/givingInterest": typeof schema_givingInterest;
  "schema/givingPlatform": typeof schema_givingPlatform;
  "schema/integrationSettings": typeof schema_integrationSettings;
  "schema/inventory": typeof schema_inventory;
  "schema/migrations": typeof schema_migrations;
  "schema/modules": typeof schema_modules;
  "schema/people": typeof schema_people;
  "schema/projects": typeof schema_projects;
  "schema/responsibilities": typeof schema_responsibilities;
  "schema/roles": typeof schema_roles;
  "schema/seatProposals": typeof schema_seatProposals;
  "schema/seatStructureLog": typeof schema_seatStructureLog;
  "schema/seats": typeof schema_seats;
  "schema/shared": typeof schema_shared;
  "schema/siteMap": typeof schema_siteMap;
  "schema/songs": typeof schema_songs;
  "schema/sponsorships": typeof schema_sponsorships;
  "schema/templates": typeof schema_templates;
  "schema/territories": typeof schema_territories;
  "schema/ticketing": typeof schema_ticketing;
  seatProposals: typeof seatProposals;
  seatStructure: typeof seatStructure;
  seats: typeof seats;
  seed: typeof seed;
  seedTicketing: typeof seedTicketing;
  setlists: typeof setlists;
  siteMap: typeof siteMap;
  songs: typeof songs;
  specializedRoles: typeof specializedRoles;
  sponsorships: typeof sponsorships;
  storage: typeof storage;
  stripe: typeof stripe;
  stripeFinance: typeof stripeFinance;
  templatePeople: typeof templatePeople;
  templateSync: typeof templateSync;
  templates: typeof templates;
  territories: typeof territories;
  ticketing: typeof ticketing;
  ticketingEmails: typeof ticketingEmails;
  ticketingSms: typeof ticketingSms;
  ticketingVerification: typeof ticketingVerification;
  transfers: typeof transfers;
  webhooks: typeof webhooks;
  work: typeof work;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
