/**
 * Curated one-time finance backfill data (2026-07-19). Private repo.
 *
 * GENESIS BANK HISTORY — the org's COMPLETE Relay bank transaction history,
 * Jun 2025 → Jun 2026, hand-categorized by the financial manager (Kansi) and
 * exported to JSON. 213 rows, verbatim: signed `amountCents` (deposits
 * positive, withdrawals negative — the runner derives `flow` + a non-negative
 * stored amount from the sign), the bank's own `description`, the `method`
 * (ACH/VISA/Wire/…), the `type` (Deposit/Withdrawal), the human `category`
 * (carried verbatim into the txn note — the app's `budgetCategories` is a
 * structured, fund-nested taxonomy this backfill deliberately does NOT invent
 * into), and the `month` bucket. See `financeGenesisBackfill.ts`.
 */
import type { GenesisBankRow } from "./types";

export const GENESIS_BANK_ROWS: GenesisBankRow[] = [
  { date: "Jun 9, 2025", month: "Jun 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 10500 },
  { date: "Jun 10, 2025", month: "Jun 2025", description: "GIVEBUTTER", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 97070 },
  { date: "Jul 15, 2025", month: "Jul 2025", description: "PARKS SPECEVNTPRMT SVCF", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -50 },
  { date: "Jul 15, 2025", month: "Jul 2025", description: "NYC PARKS SPEC EVNT PRM", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -2500 },
  { date: "Jul 15, 2025", month: "Jul 2025", description: "PARKS SPECEVNTPRMT SVCF", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -50 },
  { date: "Jul 15, 2025", month: "Jul 2025", description: "NYC PARKS SPEC EVNT PRM", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -2500 },
  { date: "Jul 17, 2025", month: "Jul 2025", description: "NYC PARKS SPEC EVNT PRM", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -2500 },
  { date: "Jul 17, 2025", month: "Jul 2025", description: "PARKS SPECEVNTPRMT SVCF", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -50 },
  { date: "Jul 23, 2025", month: "Jul 2025", description: "Megabus", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -7397 },
  { date: "Jul 26, 2025", month: "Jul 2025", description: "PETER PAN BUS LINES, IN", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -3999 },
  { date: "Jul 27, 2025", month: "Jul 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2215 },
  { date: "Jul 27, 2025", month: "Jul 2025", description: "Uber", method: "", type: "Withdrawal", category: "Transit & travel", amountCents: -4878 },
  { date: "Jul 27, 2025", month: "Jul 2025", description: "JERSEY MIKES 34102", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -18159 },
  { date: "Jul 27, 2025", month: "Jul 2025", description: "Uber", method: "", type: "Withdrawal", category: "Transit & travel", amountCents: -3026 },
  { date: "Jul 29, 2025", month: "Jul 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 39000 },
  { date: "Jul 29, 2025", month: "Jul 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 112500 },
  { date: "Jul 29, 2025", month: "Jul 2025", description: "PETER PAN BUS LINES, IN", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -4499 },
  { date: "Jul 29, 2025", month: "Jul 2025", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Aug 7, 2025", month: "Aug 2025", description: "B&H Photo Video", method: "VISA", type: "Withdrawal", category: "Equipment & hardware", amountCents: -48885 },
  { date: "Aug 12, 2025", month: "Aug 2025", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -25803 },
  { date: "Aug 12, 2025", month: "Aug 2025", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -2721 },
  { date: "Aug 16, 2025", month: "Aug 2025", description: "Facebook", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -10000 },
  { date: "Aug 29, 2025", month: "Aug 2025", description: "B&H Photo Video", method: "VISA", type: "Deposit", category: "Refunds & reimbursements", amountCents: 45765 },
  { date: "Aug 29, 2025", month: "Aug 2025", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Aug 30, 2025", month: "Aug 2025", description: "TechSoup", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -8000 },
  { date: "Aug 31, 2025", month: "Aug 2025", description: "PETER PAN BUS LINES, IN", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -4299 },
  { date: "Sep 2, 2025", month: "Sep 2025", description: "Metropolis", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2099 },
  { date: "Sep 2, 2025", month: "Sep 2025", description: "MISTER SOFTEE WESTCHEST", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -2184 },
  { date: "Sep 3, 2025", month: "Sep 2025", description: "HIBACHI GRILL & SUPREME", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -17140 },
  { date: "Sep 7, 2025", month: "Sep 2025", description: "Vistaprint", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -9536 },
  { date: "Sep 7, 2025", month: "Sep 2025", description: "OTCHEAP*CUSTOMPRINTS", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -10098 },
  { date: "Sep 7, 2025", month: "Sep 2025", description: "Printful Inc. 13", method: "", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -29889 },
  { date: "Sep 9, 2025", month: "Sep 2025", description: "OTCHEAP*CUSTOMPRINTS", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -11660 },
  { date: "Sep 13, 2025", month: "Sep 2025", description: "Signs On The Cheap", method: "VISA", type: "Deposit", category: "Refunds & reimbursements", amountCents: 10098 },
  { date: "Sep 16, 2025", month: "Sep 2025", description: "Amazon", method: "VISA", type: "Withdrawal", category: "Equipment & hardware", amountCents: -11148 },
  { date: "Sep 16, 2025", month: "Sep 2025", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -12358 },
  { date: "Sep 16, 2025", month: "Sep 2025", description: "Amazon", method: "VISA", type: "Withdrawal", category: "Equipment & hardware", amountCents: -12871 },
  { date: "Sep 16, 2025", month: "Sep 2025", description: "Amazon", method: "VISA", type: "Withdrawal", category: "Equipment & hardware", amountCents: -2405 },
  { date: "Sep 17, 2025", month: "Sep 2025", description: "1/OLUSEYI OLUJIDE", method: "Wire", type: "Deposit", category: "Income: Owner/Wire contributions", amountCents: 100000 },
  { date: "Sep 17, 2025", month: "Sep 2025", description: "Amazon", method: "VISA", type: "Withdrawal", category: "Equipment & hardware", amountCents: -16544 },
  { date: "Sep 17, 2025", month: "Sep 2025", description: "CUSTOMNIA.COM", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -11160 },
  { date: "Sep 19, 2025", month: "Sep 2025", description: "TRUIST COMMUNITY CHECKING", method: "ACH", type: "Deposit", category: "Income: Transfers in", amountCents: 50000 },
  { date: "Sep 19, 2025", month: "Sep 2025", description: "TRUIST COMMUNITY CHECKING", method: "ACH", type: "Deposit", category: "Income: Transfers in", amountCents: 50000 },
  { date: "Sep 20, 2025", month: "Sep 2025", description: "Target", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -8160 },
  { date: "Sep 20, 2025", month: "Sep 2025", description: "Instacart", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -29152 },
  { date: "Sep 20, 2025", month: "Sep 2025", description: "Target", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -10229 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2373 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2942 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Domino's Pizza", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -8480 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Domino's Pizza", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -6089 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "POSTUP STAND", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -2151 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "POSTUP STAND", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -8377 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Pizza Napoli", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -9868 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Instacart", method: "VISA", type: "Deposit", category: "Refunds & reimbursements", amountCents: 6990 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "PETER PAN BUS LINES, IN", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -3699 },
  { date: "Sep 21, 2025", month: "Sep 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2375 },
  { date: "Sep 22, 2025", month: "Sep 2025", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -290 },
  { date: "Sep 22, 2025", month: "Sep 2025", description: "The Home Depot", method: "VISA", type: "Withdrawal", category: "Equipment & hardware", amountCents: -15640 },
  { date: "Sep 29, 2025", month: "Sep 2025", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Oct 9, 2025", month: "Oct 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 113400 },
  { date: "Oct 9, 2025", month: "Oct 2025", description: "Idara (2285)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -16304 },
  { date: "Oct 10, 2025", month: "Oct 2025", description: "Peerspace", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -67640 },
  { date: "Oct 11, 2025", month: "Oct 2025", description: "Peerspace", method: "VISA", type: "Deposit", category: "Refunds & reimbursements", amountCents: 67640 },
  { date: "Oct 14, 2025", month: "Oct 2025", description: "Peerspace", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -78350 },
  { date: "Oct 22, 2025", month: "Oct 2025", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -9853 },
  { date: "Oct 29, 2025", month: "Oct 2025", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Oct 31, 2025", month: "Oct 2025", description: "Instacart", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -4727 },
  { date: "Nov 1, 2025", month: "Nov 2025", description: "City Acres Market", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -879 },
  { date: "Nov 6, 2025", month: "Nov 2025", description: "Cash App", method: "VISA", type: "Deposit", category: "Income: Donations (Cash App)", amountCents: 87060 },
  { date: "Nov 19, 2025", month: "Nov 2025", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -25569 },
  { date: "Nov 21, 2025", month: "Nov 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1438 },
  { date: "Nov 28, 2025", month: "Nov 2025", description: "Blackmagic Cloud Store", method: "", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Nov 28, 2025", month: "Nov 2025", description: "Peerspace", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -65000 },
  { date: "Nov 30, 2025", month: "Nov 2025", description: "CUSTOMNIA.COM", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -60800 },
  { date: "Dec 1, 2025", month: "Dec 2025", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -7450 },
  { date: "Dec 2, 2025", month: "Dec 2025", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -836 },
  { date: "Dec 3, 2025", month: "Dec 2025", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "Dec 4, 2025", month: "Dec 2025", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -543 },
  { date: "Dec 5, 2025", month: "Dec 2025", description: "Mentimeter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -15756 },
  { date: "Dec 7, 2025", month: "Dec 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2510 },
  { date: "Dec 7, 2025", month: "Dec 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2571 },
  { date: "Dec 7, 2025", month: "Dec 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1632 },
  { date: "Dec 8, 2025", month: "Dec 2025", description: "Peerspace", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -13688 },
  { date: "Dec 8, 2025", month: "Dec 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 365500 },
  { date: "Dec 8, 2025", month: "Dec 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 22625 },
  { date: "Dec 9, 2025", month: "Dec 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 77500 },
  { date: "Dec 9, 2025", month: "Dec 2025", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 24000 },
  { date: "Dec 11, 2025", month: "Dec 2025", description: "Paypal", method: "VISA", type: "Withdrawal", category: "Other payments (PayPal)", amountCents: -32500 },
  { date: "Dec 15, 2025", month: "Dec 2025", description: "Uber", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -3208 },
  { date: "Dec 18, 2025", month: "Dec 2025", description: "Mariam Olujide (1737)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -37600 },
  { date: "Dec 19, 2025", month: "Dec 2025", description: "VISA", method: "ACH", type: "Deposit", category: "Refunds & reimbursements", amountCents: 51399 },
  { date: "Dec 29, 2025", month: "Dec 2025", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Dec 30, 2025", month: "Dec 2025", description: "Target", method: "", type: "Withdrawal", category: "Groceries & supplies", amountCents: -5535 },
  { date: "Dec 30, 2025", month: "Dec 2025", description: "Target", method: "", type: "Withdrawal", category: "Groceries & supplies", amountCents: -12224 },
  { date: "Jan 1, 2026", month: "Jan 2026", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -7450 },
  { date: "Jan 1, 2026", month: "Jan 2026", description: "Uber", method: "", type: "Withdrawal", category: "Transit & travel", amountCents: -5308 },
  { date: "Jan 1, 2026", month: "Jan 2026", description: "Domino's Pizza", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -21715 },
  { date: "Jan 1, 2026", month: "Jan 2026", description: "Reindall Joseph (8007)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -20000 },
  { date: "Jan 2, 2026", month: "Jan 2026", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1414 },
  { date: "Jan 3, 2026", month: "Jan 2026", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "Jan 6, 2026", month: "Jan 2026", description: "Cash App", method: "VISA", type: "Deposit", category: "Income: Donations (Cash App)", amountCents: 28838 },
  { date: "Jan 6, 2026", month: "Jan 2026", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 50000 },
  { date: "Jan 6, 2026", month: "Jan 2026", description: "Givebutter", method: "ACH", type: "Deposit", category: "Income: Donations (Givebutter)", amountCents: 33000 },
  { date: "Jan 6, 2026", month: "Jan 2026", description: "Supa Media, LLC", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -5000 },
  { date: "Jan 28, 2026", month: "Jan 2026", description: "Fiverr", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -21733 },
  { date: "Jan 29, 2026", month: "Jan 2026", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Feb 1, 2026", month: "Feb 2026", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -9013 },
  { date: "Feb 1, 2026", month: "Feb 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2050 },
  { date: "Feb 1, 2026", month: "Feb 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -2050 },
  { date: "Feb 1, 2026", month: "Feb 2026", description: "Gyu-Kaku Japanese BBQ", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -20857 },
  { date: "Feb 2, 2026", month: "Feb 2026", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1427 },
  { date: "Feb 3, 2026", month: "Feb 2026", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "Feb 6, 2026", month: "Feb 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Feb 6, 2026", month: "Feb 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Feb 6, 2026", month: "Feb 2026", description: "SQ *LINCOLN NEWSSTAND I", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -3475 },
  { date: "Feb 7, 2026", month: "Feb 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Feb 7, 2026", month: "Feb 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Feb 7, 2026", month: "Feb 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Feb 7, 2026", month: "Feb 2026", description: "Jesse Awansi (3915)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -30000 },
  { date: "Feb 8, 2026", month: "Feb 2026", description: "Chick-fil-A", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -11192 },
  { date: "Feb 8, 2026", month: "Feb 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1050 },
  { date: "Feb 8, 2026", month: "Feb 2026", description: "TST* DIG INN - GARMENT", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -1551 },
  { date: "Feb 8, 2026", month: "Feb 2026", description: "GRUBHUB*EMPANADAMAMA", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -13697 },
  { date: "Feb 13, 2026", month: "Feb 2026", description: "Paypal", method: "VISA", type: "Withdrawal", category: "Other payments (PayPal)", amountCents: -12500 },
  { date: "Feb 14, 2026", month: "Feb 2026", description: "Sobechukwu (0009)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -20000 },
  { date: "Mar 1, 2026", month: "Mar 2026", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -13700 },
  { date: "Mar 1, 2026", month: "Mar 2026", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Mar 2, 2026", month: "Mar 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Mar 2, 2026", month: "Mar 2026", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1427 },
  { date: "Mar 3, 2026", month: "Mar 2026", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "Mar 6, 2026", month: "Mar 2026", description: "Uber", method: "", type: "Withdrawal", category: "Transit & travel", amountCents: -10395 },
  { date: "Mar 7, 2026", month: "Mar 2026", description: "Uber", method: "", type: "Withdrawal", category: "Transit & travel", amountCents: -1836 },
  { date: "Mar 14, 2026", month: "Mar 2026", description: "Dig Inn", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -3836 },
  { date: "Mar 14, 2026", month: "Mar 2026", description: "NYC PARKS SPEC EVNT PRM", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -2500 },
  { date: "Mar 14, 2026", month: "Mar 2026", description: "PARKS SPECEVNTPRMT SVCF", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -50 },
  { date: "Mar 15, 2026", month: "Mar 2026", description: "Simple 990", method: "", type: "Withdrawal", category: "Software & subscriptions", amountCents: -5000 },
  { date: "Mar 15, 2026", month: "Mar 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Mar 15, 2026", month: "Mar 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1000 },
  { date: "Mar 15, 2026", month: "Mar 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Mar 15, 2026", month: "Mar 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Mar 15, 2026", month: "Mar 2026", description: "Doordash", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -13074 },
  { date: "Mar 22, 2026", month: "Mar 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Mar 22, 2026", month: "Mar 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Mar 22, 2026", month: "Mar 2026", description: "Doordash", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -8085 },
  { date: "Mar 26, 2026", month: "Mar 2026", description: "OLUSEYI OLUJIDE", method: "Wire", type: "Deposit", category: "Income: Owner/Wire contributions", amountCents: 700000 },
  { date: "Mar 27, 2026", month: "Mar 2026", description: "Webflow", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1800 },
  { date: "Mar 29, 2026", month: "Mar 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1000 },
  { date: "Mar 29, 2026", month: "Mar 2026", description: "Eden Stewart (8586)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -15000 },
  { date: "Mar 29, 2026", month: "Mar 2026", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "Mar 29, 2026", month: "Mar 2026", description: "Titus Dewely (1008)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -25000 },
  { date: "Mar 29, 2026", month: "Mar 2026", description: "Andrew George (2988)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -15000 },
  { date: "Mar 31, 2026", month: "Mar 2026", description: "Isaiah Jones (8128)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -22500 },
  { date: "Apr 1, 2026", month: "Apr 2026", description: "Rehana Webb (9263)", method: "ACH", type: "Withdrawal", category: "Payments to individuals (ACH)", amountCents: -15000 },
  { date: "Apr 1, 2026", month: "Apr 2026", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -13700 },
  { date: "Apr 2, 2026", month: "Apr 2026", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1427 },
  { date: "Apr 2, 2026", month: "Apr 2026", description: "Tellap Tech", method: "", type: "Withdrawal", category: "Software & subscriptions", amountCents: -5000 },
  { date: "Apr 3, 2026", month: "Apr 2026", description: "GEN - NY", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -36489 },
  { date: "Apr 3, 2026", month: "Apr 2026", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "Apr 9, 2026", month: "Apr 2026", description: "Other", method: "", type: "Deposit", category: "Income: Other", amountCents: 5000 },
  { date: "Apr 12, 2026", month: "Apr 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Apr 12, 2026", month: "Apr 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Apr 12, 2026", month: "Apr 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Apr 13, 2026", month: "Apr 2026", description: "Supa Media, LLC", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -16020 },
  { date: "Apr 17, 2026", month: "Apr 2026", description: "Webflow", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1908 },
  { date: "Apr 19, 2026", month: "Apr 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1050 },
  { date: "Apr 21, 2026", month: "Apr 2026", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -54329 },
  { date: "Apr 21, 2026", month: "Apr 2026", description: "Tapstitch", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -62326 },
  { date: "Apr 23, 2026", month: "Apr 2026", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -43549 },
  { date: "Apr 26, 2026", month: "Apr 2026", description: "Chick-fil-A", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -12917 },
  { date: "Apr 26, 2026", month: "Apr 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Apr 26, 2026", month: "Apr 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Apr 27, 2026", month: "Apr 2026", description: "Webflow", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1908 },
  { date: "Apr 29, 2026", month: "Apr 2026", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "May 1, 2026", month: "May 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "May 1, 2026", month: "May 2026", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -13700 },
  { date: "May 2, 2026", month: "May 2026", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1424 },
  { date: "May 3, 2026", month: "May 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -1000 },
  { date: "May 3, 2026", month: "May 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "May 3, 2026", month: "May 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "May 3, 2026", month: "May 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "May 3, 2026", month: "May 2026", description: "Doordash", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -15886 },
  { date: "May 3, 2026", month: "May 2026", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "May 8, 2026", month: "May 2026", description: "DD *DOORDASH DIGINN", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -12356 },
  { date: "May 9, 2026", month: "May 2026", description: "Vistaprint", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -10554 },
  { date: "May 11, 2026", month: "May 2026", description: "Paypal", method: "VISA", type: "Withdrawal", category: "Other payments (PayPal)", amountCents: -15000 },
  { date: "May 12, 2026", month: "May 2026", description: "PARKS SPECEVNTPRMT SVCF", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -50 },
  { date: "May 12, 2026", month: "May 2026", description: "NYC PARKS SPEC EVNT PRM", method: "VISA", type: "Withdrawal", category: "Event permits (NYC Parks)", amountCents: -2500 },
  { date: "May 25, 2026", month: "May 2026", description: "Doordash", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -9147 },
  { date: "May 27, 2026", month: "May 2026", description: "Webflow", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1908 },
  { date: "May 27, 2026", month: "May 2026", description: "PRINT MOR", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -14698 },
  { date: "May 28, 2026", month: "May 2026", description: "Amazon", method: "", type: "Withdrawal", category: "Equipment & hardware", amountCents: -11705 },
  { date: "May 29, 2026", month: "May 2026", description: "Blackmagic Cloud Store", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1250 },
  { date: "May 30, 2026", month: "May 2026", description: "Target", method: "", type: "Withdrawal", category: "Groceries & supplies", amountCents: -4899 },
  { date: "May 30, 2026", month: "May 2026", description: "Target", method: "", type: "Withdrawal", category: "Groceries & supplies", amountCents: -600 },
  { date: "May 31, 2026", month: "May 2026", description: "SQ *KNICKBOKER FLOWERS", method: "VISA", type: "Withdrawal", category: "Printing, design & marketing", amountCents: -27219 },
  { date: "May 31, 2026", month: "May 2026", description: "Uber Eats", method: "", type: "Withdrawal", category: "Meals & food", amountCents: -18218 },
  { date: "May 31, 2026", month: "May 2026", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "May 31, 2026", month: "May 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "May 31, 2026", month: "May 2026", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "May 31, 2026", month: "May 2026", description: "Costco", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -75008 },
  { date: "May 31, 2026", month: "May 2026", description: "City Acres Market", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -3203 },
  { date: "May 31, 2026", month: "May 2026", description: "City Acres Market", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -2243 },
  { date: "May 31, 2026", month: "May 2026", description: "Instacart", method: "VISA", type: "Withdrawal", category: "Groceries & supplies", amountCents: -3830 },
  { date: "Jun 1, 2026", month: "Jun 2026 (partial)", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Jun 1, 2026", month: "Jun 2026 (partial)", description: "STUF STORAGE", method: "VISA", type: "Withdrawal", category: "Storage & venue rental", amountCents: -13700 },
  { date: "Jun 2, 2026", month: "Jun 2026 (partial)", description: "Target", method: "", type: "Withdrawal", category: "Groceries & supplies", amountCents: -200 },
  { date: "Jun 2, 2026", month: "Jun 2026 (partial)", description: "Google", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -1418 },
  { date: "Jun 3, 2026", month: "Jun 2026 (partial)", description: "Givebutter", method: "VISA", type: "Withdrawal", category: "Software & subscriptions", amountCents: -3380 },
  { date: "Jun 5, 2026", month: "Jun 2026 (partial)", description: "DD *DOORDASH DIGINN", method: "VISA", type: "Withdrawal", category: "Meals & food", amountCents: -16551 },
  { date: "Jun 5, 2026", month: "Jun 2026 (partial)", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
  { date: "Jun 5, 2026", month: "Jun 2026 (partial)", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Jun 5, 2026", month: "Jun 2026 (partial)", description: "MTA", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -300 },
  { date: "Jun 5, 2026", month: "Jun 2026 (partial)", description: "MTA eTix", method: "VISA", type: "Withdrawal", category: "Transit & travel", amountCents: -525 },
];
