/// <reference types="vite/client" />
import { afterEach, describe, expect, test, vi } from "vitest";
import { newT, run, setupChapter, type ChapterSetup } from "./setup.helpers";
import { anyApi } from "convex/server";
import type { Doc, Id } from "../_generated/dataModel";
import { CENTRAL } from "@events-os/shared";

/**
 * `anyApi` (not the generated `api` from `_generated/api`), deliberately:
 * this module is brand new and `_generated/api.d.ts` is regenerated by
 * `npx convex dev`/`codegen` against a live deployment, which this sandbox
 * doesn't have and which this task's file-ownership rule forbids editing by
 * hand anyway. `anyApi` is Convex's own supported no-codegen escape hatch
 * (`convex/server`'s doc comment: "for projects not using code generation")
 * — same runtime `FunctionReference`, and it still typechecks. Delete this
 * note (and switch back to the generated `api`) once a normal `convex dev`
 * cycle has regenerated `_generated/api.d.ts` to include this module.
 */
const removeUnexecutedBalanceSettlements = anyApi.removeUnexecutedBalanceSettlements
  .removeUnexecutedBalanceSettlements;

/**
 * `removeUnexecutedBalanceSettlements` — the one-time backlog-delete runner.
 *
 * Mirrors `reverseExcludedSettlementLoop.test.ts`'s spirit (the module's
 * ONE non-obvious precondition is what actually decides correctness) but
 * this module has several equally load-bearing guards, since it deletes
 * WHOLE rows rather than excluding one hard-coded pair — so each guard gets
 * its own test: the externalId refusal, the leg-count anomaly refusal, the
 * enforced book-value-unchanged guard, dry-run-writes-nothing, execute
 * actually deletes, and re-run-is-a-no-op.
 *
 * Delete this file with the module.
 */

// Mutable knob the "book value guard trips" test uses to force
// `signedBookCents` to disagree with reality for one call, without changing
// what every other test in this file sees. `importOriginal` keeps every
// other export (there's only the one) wired to the REAL implementation.
let forcedSignedBookCents: number | null = null;
vi.mock("../lib/bookBalance", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../lib/bookBalance")>();
  return {
    ...actual,
    signedBookCents: (tr: Doc<"transactions">) =>
      forcedSignedBookCents != null ? forcedSignedBookCents : actual.signedBookCents(tr),
  };
});
afterEach(() => {
  forcedSignedBookCents = null;
});

async function seedSelfPerson(s: ChapterSetup): Promise<Id<"people">> {
  return run(s.t, (ctx) =>
    ctx.db.insert("people", {
      chapterId: s.chapterId,
      name: "Caller",
      userId: s.userId,
      isTeamMember: true,
      createdAt: Date.now(),
    }),
  );
}

/** Central ED — passes `isCentralEdOrFm`/`requireReconciliationAudit`, the
 *  gate this module uses. Mirrors `reconciliationEngine.test.ts`'s helper. */
async function asCentralEd(s: ChapterSetup): Promise<Id<"people">> {
  const personId = await seedSelfPerson(s);
  await run(s.t, async (ctx) => {
    await ctx.db.insert("specializedRoles", {
      personId,
      title: "executive_director",
      roleKind: "leadership",
      scope: "central",
      createdAt: Date.now(),
    });
  });
  return personId;
}

/** A clean `balsettle-…` pair, in the exact shape
 *  `lib/transferPair.ts#recordTransferPair` writes for `settleChapterBalances`. */
async function seedBalanceSettlementPair(
  s: ChapterSetup,
  args: {
    date: string;
    amountCents: number;
    postedAt?: number;
    externalIdOnChapterLeg?: string;
    externalIdOnCentralLeg?: string;
    originOverride?: string;
    amountOverrideOnChapterLeg?: number;
  },
): Promise<{ groupId: string; legIds: Id<"transactions">[] }> {
  const groupId = `balsettle-${s.chapterId}-${args.date}`;
  const postedAt = args.postedAt ?? Date.now();
  const legIds = await run(s.t, async (ctx) => {
    const ids: Id<"transactions">[] = [];
    for (const scope of [CENTRAL, s.chapterId] as const) {
      const isChapterLeg = scope === s.chapterId;
      ids.push(
        await ctx.db.insert("transactions", {
          chapterId: scope,
          source: "transfer",
          flow: "transfer",
          amountCents:
            isChapterLeg && args.amountOverrideOnChapterLeg != null
              ? args.amountOverrideOnChapterLeg
              : args.amountCents,
          currency: "usd",
          postedAt,
          status: "reconciled",
          transferGroupId: groupId,
          transferDirection: "central_to_chapter",
          transferOrigin: (args.originOverride ??
            "balance_settlement") as "balance_settlement",
          externalId: isChapterLeg
            ? args.externalIdOnChapterLeg
            : args.externalIdOnCentralLeg,
          createdAt: Date.now(),
        }),
      );
    }
    return ids;
  });
  return { groupId, legIds };
}

async function getRows(
  s: ChapterSetup,
  ids: Id<"transactions">[],
): Promise<(Doc<"transactions"> | null)[]> {
  return run(s.t, async (ctx) => Promise.all(ids.map((id) => ctx.db.get(id))));
}

describe("removeUnexecutedBalanceSettlements — auth", () => {
  test("refuses a caller who isn't ED/FM", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await seedSelfPerson(s); // a roster person, but no ED/FM title
    await expect(
      s.as.mutation(removeUnexecutedBalanceSettlements, {}),
    ).rejects.toThrow(/Executive Director and Financial Manager/i);
  });
});

describe("removeUnexecutedBalanceSettlements — happy path", () => {
  test("dry run finds a qualifying pair and deletes nothing", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const { groupId, legIds } = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 461_690,
    });

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      {},
    );

    expect(result.dryRun).toBe(true);
    expect(result.refused).toBe(false);
    expect(result.problems).toEqual([]);
    expect(result.totalSignedBookCents).toBe(0);
    expect(result.deletedLegs).toBe(0);
    expect(result.candidates).toEqual([
      {
        transferGroupId: groupId,
        chapterId: s.chapterId,
        postedAt: expect.any(Number),
        amountCents: 461_690,
        legCount: 2,
      },
    ]);

    const rows = await getRows(s, legIds);
    expect(rows.every((r) => r != null)).toBe(true);
  });

  test("execute: true deletes both legs of a qualifying pair", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const { legIds } = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 461_690,
    });

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(result.dryRun).toBe(false);
    expect(result.refused).toBe(false);
    expect(result.deletedLegs).toBe(2);
    expect(result.candidates).toHaveLength(1);

    const rows = await getRows(s, legIds);
    expect(rows.every((r) => r == null)).toBe(true);
  });

  test("re-running execute after a successful run is a clean no-op", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    await seedBalanceSettlementPair(s, { date: "2026-08-10", amountCents: 461_690 });

    await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );
    const second = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(second.candidates).toEqual([]);
    expect(second.deletedLegs).toBe(0);
    expect(second.problems).toEqual([]);
    expect(second.refused).toBe(false);
  });

  test("scopes to one chapter and a date range", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const inScope = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 100_000,
      postedAt: Date.UTC(2026, 7, 10),
    });
    const outOfScope = await seedBalanceSettlementPair(s, {
      date: "2026-08-20",
      amountCents: 200_000,
      postedAt: Date.UTC(2026, 7, 20),
    });

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      {
        chapterId: s.chapterId,
        fromDateMs: Date.UTC(2026, 7, 1),
        toDateMs: Date.UTC(2026, 7, 15),
      },
    );

    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0].transferGroupId).toBe(inScope.groupId);
    expect(result.candidates[0].transferGroupId).not.toBe(outOfScope.groupId);
  });
});

describe("removeUnexecutedBalanceSettlements — refusals", () => {
  test("refuses (and deletes nothing) when either leg carries an externalId — real cash moved", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const { legIds } = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 461_690,
      externalIdOnChapterLeg: "increase_txn_abc123",
    });

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(result.refused).toBe(true);
    expect(result.deletedLegs).toBe(0);
    expect(result.candidates).toEqual([]);
    expect(result.problems.some((p: string) => /externalId/i.test(p))).toBe(true);

    const rows = await getRows(s, legIds);
    expect(rows.every((r) => r != null)).toBe(true);
  });

  test("refuses a 3-leg group instead of guessing which two to delete", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const { groupId, legIds } = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 461_690,
    });
    // A stray third leg on the same group id — the anomaly this must refuse on.
    const strayId = await run(s.t, (ctx) =>
      ctx.db.insert("transactions", {
        chapterId: s.chapterId,
        source: "transfer",
        flow: "transfer",
        amountCents: 461_690,
        postedAt: Date.now(),
        status: "reconciled",
        transferGroupId: groupId,
        transferOrigin: "balance_settlement",
        createdAt: Date.now(),
      }),
    );

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(result.refused).toBe(true);
    expect(result.deletedLegs).toBe(0);
    expect(result.problems.some((p: string) => p.includes("expected exactly 2"))).toBe(true);

    const rows = await getRows(s, [...legIds, strayId]);
    expect(rows.every((r) => r != null)).toBe(true);
  });

  test("refuses an orphan 1-leg group", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const orphanGroupId = `balsettle-${s.chapterId}-2026-08-11`;
    const orphanId = await run(s.t, (ctx) =>
      ctx.db.insert("transactions", {
        chapterId: s.chapterId,
        source: "transfer",
        flow: "transfer",
        amountCents: 12_345,
        postedAt: Date.now(),
        status: "reconciled",
        transferGroupId: orphanGroupId,
        transferOrigin: "balance_settlement",
        createdAt: Date.now(),
      }),
    );

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(result.refused).toBe(true);
    expect(result.deletedLegs).toBe(0);
    expect(result.problems.some((p: string) => p.includes("expected exactly 2"))).toBe(true);

    const row = await run(s.t, (ctx) => ctx.db.get(orphanId));
    expect(row).not.toBeNull();
  });

  test("refuses a pair whose legs disagree on amount", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const { legIds } = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 461_690,
      amountOverrideOnChapterLeg: 461_691, // one cent off
    });

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(result.refused).toBe(true);
    expect(result.deletedLegs).toBe(0);
    expect(result.problems.some((p: string) => /disagree on amount/.test(p))).toBe(true);

    const rows = await getRows(s, legIds);
    expect(rows.every((r) => r != null)).toBe(true);
  });

  test("the signedBookCents-total guard trips and refuses, even for an otherwise-clean pair", async () => {
    const t = newT();
    const s = await setupChapter(t);
    await asCentralEd(s);
    const { legIds } = await seedBalanceSettlementPair(s, {
      date: "2026-08-10",
      amountCents: 461_690,
    });

    forcedSignedBookCents = 4_616_90; // pretend this leg moved book value

    const result = await s.as.mutation(
      removeUnexecutedBalanceSettlements,
      { execute: true },
    );

    expect(result.refused).toBe(true);
    expect(result.deletedLegs).toBe(0);
    expect(result.totalSignedBookCents).not.toBe(0);
    expect(result.problems.some((p: string) => /change total book value/.test(p))).toBe(true);

    const rows = await getRows(s, legIds);
    expect(rows.every((r) => r != null)).toBe(true);
  });
});
