name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: Supa-Media/supa-framework/.github/workflows/ci.yml@fix/ci-github-packages-auth
    with:
      app-slug: "events-os"
      strictness: "standard"
    secrets: inherit
